# Copyright (c) 2024-2026 Pikar AI. All rights reserved.
# Proprietary and confidential. See LICENSE file for details.

"""Admin Agent tools package."""

from app.agents.admin.tools.billing import (
    assess_refund_risk,
    detect_analytics_anomalies,
    forecast_revenue,
    generate_executive_summary,
    get_billing_metrics,
    get_plan_distribution,
    issue_refund,
)
from app.agents.admin.tools.analytics import (
    generate_report,
    get_agent_effectiveness,
    get_engagement_report,
    get_usage_stats,
)
from app.agents.admin.tools.config import (
    assess_config_impact,
    get_agent_config,
    get_autonomy_permissions,
    get_config_history,
    get_feature_flags,
    recommend_config_rollback,
    rollback_agent_config,
    toggle_feature_flag,
    update_agent_config,
    update_autonomy_permission,
)
from app.agents.admin.tools.health import check_system_health
from app.agents.admin.tools.integrations import (
    github_get_pr_status,
    github_list_prs,
    posthog_get_insights,
    posthog_query_events,
    sentry_get_issue_detail,
    sentry_get_issues,
)
from app.agents.admin.tools.knowledge import (
    check_knowledge_duplicate,
    delete_knowledge_entry,
    get_knowledge_stats,
    list_knowledge_entries,
    recommend_chunking_strategy,
    search_knowledge,
    upload_knowledge,
    validate_knowledge_relevance,
)
from app.agents.admin.tools.monitoring import (
    check_error_logs,
    check_rate_limits,
    get_active_incidents,
    get_api_health_history,
    get_api_health_summary,
    get_incident_detail,
    run_diagnostic,
)
from app.agents.admin.tools.users import (
    change_user_persona,
    get_user_detail,
    impersonate_user,
    list_users,
    suspend_user,
    unsuspend_user,
)

__all__ = [
    "assess_config_impact",
    "assess_refund_risk",
    "change_user_persona",
    "check_error_logs",
    "check_knowledge_duplicate",
    "check_rate_limits",
    "check_system_health",
    "delete_knowledge_entry",
    "detect_analytics_anomalies",
    "forecast_revenue",
    "generate_executive_summary",
    "generate_report",
    "get_billing_metrics",
    "get_active_incidents",
    "get_agent_config",
    "get_agent_effectiveness",
    "get_api_health_history",
    "get_api_health_summary",
    "get_autonomy_permissions",
    "get_config_history",
    "get_engagement_report",
    "get_feature_flags",
    "get_incident_detail",
    "get_knowledge_stats",
    "get_plan_distribution",
    "get_usage_stats",
    "get_user_detail",
    "github_get_pr_status",
    "github_list_prs",
    "impersonate_user",
    "issue_refund",
    "list_knowledge_entries",
    "list_users",
    "posthog_get_insights",
    "posthog_query_events",
    "recommend_chunking_strategy",
    "recommend_config_rollback",
    "rollback_agent_config",
    "run_diagnostic",
    "search_knowledge",
    "sentry_get_issue_detail",
    "sentry_get_issues",
    "suspend_user",
    "toggle_feature_flag",
    "unsuspend_user",
    "update_agent_config",
    "update_autonomy_permission",
    "upload_knowledge",
    "validate_knowledge_relevance",
]
