"""PWA Generator — produces manifest.json, service worker, and index.html in a ZIP.

Generates a fully installable Progressive Web App package from HTML content
and an optional design system. No external dependencies — uses stdlib only.
"""

import io
import json
import zipfile

# ---------------------------------------------------------------------------
# Service worker (cache-first strategy, hand-written — no workbox dependency)
# ---------------------------------------------------------------------------

_SERVICE_WORKER = """\
const CACHE_NAME = 'v1';
const STATIC_ASSETS = ['/', '/index.html'];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(STATIC_ASSETS))
  );
});

self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request).then(cached => cached || fetch(event.request))
  );
});
"""


# ---------------------------------------------------------------------------
# Manifest builder
# ---------------------------------------------------------------------------


def _build_manifest(app_name: str, theme_color: str, bg_color: str) -> dict:
    """Build a valid PWA manifest dict.

    Args:
        app_name: Human-readable app name.
        theme_color: Hex colour for browser chrome (e.g. ``#000000``).
        bg_color: Hex splash-screen background colour (e.g. ``#ffffff``).

    Returns:
        Manifest dict ready for JSON serialisation.
    """
    return {
        "name": app_name,
        "short_name": app_name[:12],
        "description": f"{app_name} — generated by Pikar AI",
        "start_url": "/",
        "display": "standalone",
        "background_color": bg_color or "#ffffff",
        "theme_color": theme_color or "#000000",
        "icons": [
            {"src": "/icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "/icon-512.png", "sizes": "512x512", "type": "image/png"},
            {
                "src": "/icon-512.png",
                "sizes": "512x512",
                "type": "image/png",
                "purpose": "maskable",
            },
        ],
        "categories": ["productivity"],
    }


# ---------------------------------------------------------------------------
# index.html builder
# ---------------------------------------------------------------------------


def _build_index_html(app_name: str, theme_color: str, html_content: str) -> str:
    """Build a PWA-ready index.html with iOS meta tags and SW registration.

    Args:
        app_name: Used for ``<title>`` and Apple meta tags.
        theme_color: Used for ``<meta name="theme-color">`` tag.
        html_content: Body content to embed.

    Returns:
        Full HTML string.
    """
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="theme-color" content="{theme_color}">
  <link rel="manifest" href="manifest.json">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta name="apple-mobile-web-app-title" content="{app_name}">
  <link rel="apple-touch-icon" href="/icon-192.png">
  <title>{app_name}</title>
  <script>
    if ('serviceWorker' in navigator) {{
      navigator.serviceWorker.register('/sw.js');
    }}
  </script>
</head>
<body>
{html_content}
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


async def generate_pwa_zip(
    app_name: str,
    html_content: str,
    design_system: dict | None = None,
) -> bytes:
    """Generate an in-memory ZIP containing a complete PWA package.

    Produces three files:
    - ``manifest.json`` — Web App Manifest with icons, colours, and metadata.
    - ``sw.js`` — Minimal cache-first service worker (no external dependencies).
    - ``index.html`` — Entry point with iOS meta tags and SW registration.

    Args:
        app_name: Name shown in the browser and home-screen icon.
        html_content: HTML to embed inside the ``<body>`` of index.html.
        design_system: Optional dict with ``theme_color`` and ``background_color``
            keys to use for manifest and meta tags.  Defaults to black/white.

    Returns:
        Raw ZIP bytes suitable for direct download or Supabase Storage upload.
    """
    ds = design_system or {}
    theme_color: str = ds.get("theme_color", "#000000") or "#000000"
    bg_color: str = ds.get("background_color", "#ffffff") or "#ffffff"

    manifest = _build_manifest(app_name, theme_color, bg_color)
    index_html = _build_index_html(app_name, theme_color, html_content)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("manifest.json", json.dumps(manifest, indent=2))
        zf.writestr("sw.js", _SERVICE_WORKER)
        zf.writestr("index.html", index_html)
    buf.seek(0)
    return buf.read()
