# Copyright (c) 2024-2026 Pikar AI. All rights reserved.
# Proprietary and confidential. See LICENSE file for details.

"""Custom Skills Package.
This directory contains user-defined skills generated by the Skill Builder.
"""
