# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

"""Gmail service for email operations.

Enables agents to send emails for:
- Report delivery
- Notifications
- Follow-ups
"""

import base64
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from typing import Any
from dataclasses import dataclass
import os

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build, Resource



@dataclass
class EmailMessage:
    """Represents an email message."""
    to: list[str]
    subject: str
    body: str
    body_html: str | None = None
    cc: list[str] | None = None
    bcc: list[str] | None = None
    attachments: list[str] | None = None


class GmailService:
    """Service for Gmail operations.
    
    Provides methods for:
    - Sending emails with attachments
    - Report delivery
    """
    
    def __init__(self, credentials: Credentials):
        """Initialize with Google OAuth credentials."""
        self.credentials = credentials
        self._service: Resource | None = None
    
    @property
    def service(self) -> Resource:
        """Lazy-load Gmail API service."""
        if self._service is None:
            self._service = build("gmail", "v1", credentials=self.credentials)
        return self._service
    
    def send_email(
        self,
        to: list[str],
        subject: str,
        body: str,
        body_html: str | None = None,
        cc: list[str] | None = None,
        attachments: list[str] | None = None,
    ) -> dict[str, Any]:
        """Send an email.
        
        Args:
            to: List of recipient email addresses.
            subject: Email subject line.
            body: Plain text body.
            body_html: Optional HTML body.
            cc: Optional CC recipients.
            attachments: Optional list of file paths to attach.
            
        Returns:
            Dict with send status and message ID.
        """
        # Create message
        if body_html:
            message = MIMEMultipart("alternative")
            message.attach(MIMEText(body, "plain"))
            message.attach(MIMEText(body_html, "html"))
        else:
            message = MIMEMultipart()
            message.attach(MIMEText(body, "plain"))
        
        message["To"] = ", ".join(to)
        message["Subject"] = subject
        
        if cc:
            message["Cc"] = ", ".join(cc)
        
        # Add attachments
        if attachments:
            for filepath in attachments:
                if os.path.exists(filepath):
                    filename = os.path.basename(filepath)
                    with open(filepath, "rb") as f:
                        part = MIMEBase("application", "octet-stream")
                        part.set_payload(f.read())
                    encoders.encode_base64(part)
                    part.add_header(
                        "Content-Disposition",
                        f"attachment; filename={filename}",
                    )
                    message.attach(part)
        
        # Encode and send
        raw = base64.urlsafe_b64encode(message.as_bytes()).decode()
        
        result = self.service.users().messages().send(
            userId="me",
            body={"raw": raw},
        ).execute()
        
        return {
            "status": "success",
            "message_id": result.get("id"),
            "thread_id": result.get("threadId"),
        }
    
    def send_report(
        self,
        recipients: list[str],
        report_title: str,
        summary: str,
        file_path: str,
    ) -> dict[str, Any]:
        """Send a report email with attachment.
        
        Args:
            recipients: Email addresses to send to.
            report_title: Title for the email subject.
            summary: Brief summary of the report.
            file_path: Path to the report file.
            
        Returns:
            Send status.
        """
        file_ext = os.path.splitext(file_path)[1].lower()
        format_name = {
            ".pptx": "PowerPoint",
            ".pdf": "PDF",
            ".xlsx": "Excel",
        }.get(file_ext, "Report")
        
        body = f"""
Hello,

Your {report_title} is ready.

{summary}

Please find the {format_name} report attached.

---
This report was automatically generated by Pikar AI.
"""
        
        body_html = f"""
<html>
<body>
<p>Hello,</p>
<p>Your <strong>{report_title}</strong> is ready.</p>
<p>{summary}</p>
<p>Please find the {format_name} report attached.</p>
<hr>
<p style="color: #888; font-size: 12px;">
This report was automatically generated by Pikar AI.
</p>
</body>
</html>
"""
        
        return self.send_email(
            to=recipients,
            subject=f"📊 {report_title}",
            body=body,
            body_html=body_html,
            attachments=[file_path],
        )


def get_gmail_service(credentials: Credentials) -> GmailService:
    """Get Gmail service instance."""
    return GmailService(credentials)
