/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as activity from "../activity.js";
import type * as activityFeed from "../activityFeed.js";
import type * as admin from "../admin.js";
import type * as adminAssistant from "../adminAssistant.js";
import type * as adminAuth from "../adminAuth.js";
import type * as adminAuthData from "../adminAuthData.js";
import type * as adminPasswordReset from "../adminPasswordReset.js";
import type * as adminPasswordResetData from "../adminPasswordResetData.js";
import type * as adminUsers from "../adminUsers.js";
import type * as adminUsersActions from "../adminUsersActions.js";
import type * as agentDatasets from "../agentDatasets.js";
import type * as agentMemory from "../agentMemory.js";
import type * as agentOrchestration from "../agentOrchestration.js";
import type * as agentOrchestrationData from "../agentOrchestrationData.js";
import type * as agentPerformance from "../agentPerformance.js";
import type * as agentPerformance_costForecasting from "../agentPerformance/costForecasting.js";
import type * as agentPerformance_predictive from "../agentPerformance/predictive.js";
import type * as agentProfile from "../agentProfile.js";
import type * as agentRouter from "../agentRouter.js";
import type * as aiAgents from "../aiAgents.js";
import type * as analytics_capacity from "../analytics/capacity.js";
import type * as analytics_churn from "../analytics/churn.js";
import type * as analytics_cohorts from "../analytics/cohorts.js";
import type * as analytics_funnel from "../analytics/funnel.js";
import type * as analytics_ltv from "../analytics/ltv.js";
import type * as analytics_optimization from "../analytics/optimization.js";
import type * as analytics_predictiveROI from "../analytics/predictiveROI.js";
import type * as analytics_retention from "../analytics/retention.js";
import type * as analytics_teamVelocity from "../analytics/teamVelocity.js";
import type * as analyticsEngine from "../analyticsEngine.js";
import type * as apiSdk from "../apiSdk.js";
import type * as apiVersions from "../apiVersions.js";
import type * as approvalAnalytics from "../approvalAnalytics.js";
import type * as approvals from "../approvals.js";
import type * as audit from "../audit.js";
import type * as audit_complianceReports from "../audit/complianceReports.js";
import type * as audit_export from "../audit/export.js";
import type * as audit_retention from "../audit/retention.js";
import type * as audit_search from "../audit/search.js";
import type * as auditActions from "../auditActions.js";
import type * as auth from "../auth.js";
import type * as auth_emailOtp from "../auth/emailOtp.js";
import type * as authCleanup from "../authCleanup.js";
import type * as billing from "../billing.js";
import type * as billingInternal from "../billingInternal.js";
import type * as brainDumps from "../brainDumps.js";
import type * as brandBuilder from "../brandBuilder.js";
import type * as branding from "../branding.js";
import type * as brands from "../brands.js";
import type * as businesses from "../businesses.js";
import type * as calendar from "../calendar.js";
import type * as calendar_calendarIntegrations from "../calendar/calendarIntegrations.js";
import type * as calendar_googleCalendar from "../calendar/googleCalendar.js";
import type * as calendar_outlookCalendar from "../calendar/outlookCalendar.js";
import type * as campaigns_mutations from "../campaigns/mutations.js";
import type * as campaigns_orchestration from "../campaigns/orchestration.js";
import type * as campaigns_templates from "../campaigns/templates.js";
import type * as capa from "../capa.js";
import type * as chunking from "../chunking.js";
import type * as complianceReports from "../complianceReports.js";
import type * as contacts from "../contacts.js";
import type * as contactsActions from "../contactsActions.js";
import type * as contentCapsules from "../contentCapsules.js";
import type * as contentCapsulesData from "../contentCapsulesData.js";
import type * as crisisManagement from "../crisisManagement.js";
import type * as crmIntegrations from "../crmIntegrations.js";
import type * as crmSync from "../crmSync.js";
import type * as cron from "../cron.js";
import type * as customApis from "../customApis.js";
import type * as customApis_versioning from "../customApis/versioning.js";
import type * as customerJourney from "../customerJourney.js";
import type * as customerJourney_analytics from "../customerJourney/analytics.js";
import type * as customerJourney_stages from "../customerJourney/stages.js";
import type * as customerJourney_triggers from "../customerJourney/triggers.js";
import type * as customerSegmentation from "../customerSegmentation.js";
import type * as customerSegmentation_actions from "../customerSegmentation/actions.js";
import type * as customerSegmentation_rules from "../customerSegmentation/rules.js";
import type * as customerSegmentation_solopreneur from "../customerSegmentation/solopreneur.js";
import type * as customerSegmentationData from "../customerSegmentationData.js";
import type * as data_agentCatalogSeed from "../data/agentCatalogSeed.js";
import type * as data_playbooksSeed from "../data/playbooksSeed.js";
import type * as dataWarehouse from "../dataWarehouse.js";
import type * as dataWarehouse_analytics from "../dataWarehouse/analytics.js";
import type * as dataWarehouse_dataExports from "../dataWarehouse/dataExports.js";
import type * as dataWarehouse_dataQuality from "../dataWarehouse/dataQuality.js";
import type * as dataWarehouse_dataSources from "../dataWarehouse/dataSources.js";
import type * as dataWarehouse_etlPipelines from "../dataWarehouse/etlPipelines.js";
import type * as dataWarehouse_governance from "../dataWarehouse/governance.js";
import type * as dataWarehouse_index from "../dataWarehouse/index.js";
import type * as dataWarehouse_lineage from "../dataWarehouse/lineage.js";
import type * as dataWarehouse_streaming from "../dataWarehouse/streaming.js";
import type * as demoVideos from "../demoVideos.js";
import type * as departmentBudgets from "../departmentBudgets.js";
import type * as departmentBudgets_forecasting from "../departmentBudgets/forecasting.js";
import type * as departmentBudgets_optimization from "../departmentBudgets/optimization.js";
import type * as departmentKpis from "../departmentKpis.js";
import type * as departmentKpis_alerts from "../departmentKpis/alerts.js";
import type * as departmentKpis_targets from "../departmentKpis/targets.js";
import type * as departmentKpis_tracking from "../departmentKpis/tracking.js";
import type * as diagnostics from "../diagnostics.js";
import type * as docProcessing from "../docProcessing.js";
import type * as docs from "../docs.js";
import type * as docsFaqs from "../docsFaqs.js";
import type * as docsInternal from "../docsInternal.js";
import type * as docsVideos from "../docsVideos.js";
import type * as emailAnalytics from "../emailAnalytics.js";
import type * as emailConfig from "../emailConfig.js";
import type * as emailDraftAgent from "../emailDraftAgent.js";
import type * as emailDraftAgentData from "../emailDraftAgentData.js";
import type * as emailDrafts from "../emailDrafts.js";
import type * as emailTracking from "../emailTracking.js";
import type * as emails from "../emails.js";
import type * as emailsActions from "../emailsActions.js";
import type * as enableFeatures from "../enableFeatures.js";
import type * as enterpriseMetrics from "../enterpriseMetrics.js";
import type * as enterpriseSecurity from "../enterpriseSecurity.js";
import type * as enterpriseSupport from "../enterpriseSupport.js";
import type * as entitlements from "../entitlements.js";
import type * as evals from "../evals.js";
import type * as evalsInternal from "../evalsInternal.js";
import type * as experiments from "../experiments.js";
import type * as experimentsActions from "../experimentsActions.js";
import type * as featureFlags from "../featureFlags.js";
import type * as files from "../files.js";
import type * as governance from "../governance.js";
import type * as governance_autoEnforcement from "../governance/autoEnforcement.js";
import type * as governance_remediation from "../governance/remediation.js";
import type * as governance_violations from "../governance/violations.js";
import type * as governanceAutomation from "../governanceAutomation.js";
import type * as governanceRules from "../governanceRules.js";
import type * as health from "../health.js";
import type * as helpCoach_assistant from "../helpCoach/assistant.js";
import type * as helpCoach_tutorials from "../helpCoach/tutorials.js";
import type * as http from "../http.js";
import type * as init from "../init.js";
import type * as initWorkspaceDefaults from "../initWorkspaceDefaults.js";
import type * as initiativeJourney from "../initiativeJourney.js";
import type * as initiatives from "../initiatives.js";
import type * as inspector from "../inspector.js";
import type * as integrationPlatform from "../integrationPlatform.js";
import type * as integrationPlatform_billing from "../integrationPlatform/billing.js";
import type * as integrationPlatform_costs from "../integrationPlatform/costs.js";
import type * as invoices from "../invoices.js";
import type * as invoicesActions from "../invoicesActions.js";
import type * as kgraph from "../kgraph.js";
import type * as kms from "../kms.js";
import type * as kmsActions from "../kmsActions.js";
import type * as knowledge from "../knowledge.js";
import type * as kpis from "../kpis.js";
import type * as landingChat from "../landingChat.js";
import type * as learningContent from "../learningContent.js";
import type * as learningContentActions from "../learningContentActions.js";
import type * as lib_aiAgents_admin from "../lib/aiAgents/admin.js";
import type * as lib_aiAgents_config from "../lib/aiAgents/config.js";
import type * as lib_aiAgents_datasets from "../lib/aiAgents/datasets.js";
import type * as lib_aiAgents_publish from "../lib/aiAgents/publish.js";
import type * as lib_aiAgents_training from "../lib/aiAgents/training.js";
import type * as lib_aiAgents_versions from "../lib/aiAgents/versions.js";
import type * as lib_errors from "../lib/errors.js";
import type * as locations_analytics from "../locations/analytics.js";
import type * as locations_compliance from "../locations/compliance.js";
import type * as locations_management from "../locations/management.js";
import type * as notifications from "../notifications.js";
import type * as notifications_realtime from "../notifications/realtime.js";
import type * as nudges from "../nudges.js";
import type * as oidc from "../oidc.js";
import type * as oidcActions from "../oidcActions.js";
import type * as onboarding from "../onboarding.js";
import type * as openai from "../openai.js";
import type * as openapi from "../openapi.js";
import type * as passwordAuth from "../passwordAuth.js";
import type * as passwordAuthActions from "../passwordAuthActions.js";
import type * as passwordAuthData from "../passwordAuthData.js";
import type * as payments_paypal from "../payments/paypal.js";
import type * as payments_stripe from "../payments/stripe.js";
import type * as playbookExecutions from "../playbookExecutions.js";
import type * as playbookVersions from "../playbookVersions.js";
import type * as playbooks from "../playbooks.js";
import type * as policyManagement from "../policyManagement.js";
import type * as portfolioManagement from "../portfolioManagement.js";
import type * as portfolioManagement_analytics from "../portfolioManagement/analytics.js";
import type * as portfolioManagement_optimization from "../portfolioManagement/optimization.js";
import type * as portfolioManagement_predictive from "../portfolioManagement/predictive.js";
import type * as rateLimiting from "../rateLimiting.js";
import type * as resources_allocation from "../resources/allocation.js";
import type * as resources_optimization from "../resources/optimization.js";
import type * as revenueAttribution from "../revenueAttribution.js";
import type * as risk_mitigation from "../risk/mitigation.js";
import type * as risk_reporting from "../risk/reporting.js";
import type * as risk_scenarios from "../risk/scenarios.js";
import type * as riskAnalytics from "../riskAnalytics.js";
import type * as roiCalculations from "../roiCalculations.js";
import type * as sales_activities from "../sales/activities.js";
import type * as sales_forecasting from "../sales/forecasting.js";
import type * as sales_pipeline from "../sales/pipeline.js";
import type * as saml from "../saml.js";
import type * as samlActions from "../samlActions.js";
import type * as schedule from "../schedule.js";
import type * as scheduling_assistant from "../scheduling/assistant.js";
import type * as scheduling_availability from "../scheduling/availability.js";
import type * as schema_activity from "../schema/activity.js";
import type * as schema_admin from "../schema/admin.js";
import type * as schema_agents from "../schema/agents.js";
import type * as schema_calendar from "../schema/calendar.js";
import type * as schema_contacts from "../schema/contacts.js";
import type * as schema_content from "../schema/content.js";
import type * as schema_core from "../schema/core.js";
import type * as schema_demoVideos from "../schema/demoVideos.js";
import type * as schema_docs from "../schema/docs.js";
import type * as schema_email from "../schema/email.js";
import type * as schema_enterprise from "../schema/enterprise.js";
import type * as schema_index from "../schema/index.js";
import type * as schema_initiatives from "../schema/initiatives.js";
import type * as schema_integrations from "../schema/integrations.js";
import type * as schema_kpi from "../schema/kpi.js";
import type * as schema_onboarding from "../schema/onboarding.js";
import type * as schema_orchestration from "../schema/orchestration.js";
import type * as schema_risk from "../schema/risk.js";
import type * as schema_security from "../schema/security.js";
import type * as schema_social from "../schema/social.js";
import type * as schema_support from "../schema/support.js";
import type * as schema_team from "../schema/team.js";
import type * as schema_testing from "../schema/testing.js";
import type * as schema_vectors from "../schema/vectors.js";
import type * as schema_whiteLabel from "../schema/whiteLabel.js";
import type * as schema_wins from "../schema/wins.js";
import type * as schema_workflows from "../schema/workflows.js";
import type * as scim from "../scim.js";
import type * as search from "../search.js";
import type * as security_compliance from "../security/compliance.js";
import type * as security_incidents from "../security/incidents.js";
import type * as security_threats from "../security/threats.js";
import type * as seed from "../seed.js";
import type * as setupWizard from "../setupWizard.js";
import type * as setupWizardData from "../setupWizardData.js";
import type * as socialAnalytics from "../socialAnalytics.js";
import type * as socialAnalyticsAdvanced from "../socialAnalyticsAdvanced.js";
import type * as socialAnalyticsAdvanced_crisis from "../socialAnalyticsAdvanced/crisis.js";
import type * as socialAnalyticsAdvanced_listening from "../socialAnalyticsAdvanced/listening.js";
import type * as socialAnalyticsAdvanced_responses from "../socialAnalyticsAdvanced/responses.js";
import type * as socialApiConfigs from "../socialApiConfigs.js";
import type * as socialContentAgent from "../socialContentAgent.js";
import type * as socialContentAgent_analytics from "../socialContentAgent/analytics.js";
import type * as socialContentAgent_optimization from "../socialContentAgent/optimization.js";
import type * as socialIntegrations from "../socialIntegrations.js";
import type * as socialIntegrations_oauth from "../socialIntegrations/oauth.js";
import type * as socialIntegrations_webhooks from "../socialIntegrations/webhooks.js";
import type * as socialIntegrationsActions from "../socialIntegrationsActions.js";
import type * as socialMediaDocs from "../socialMediaDocs.js";
import type * as socialPosts from "../socialPosts.js";
import type * as socialPostsCron from "../socialPostsCron.js";
import type * as solopreneur from "../solopreneur.js";
import type * as strategicInitiatives from "../strategicInitiatives.js";
import type * as support_autoResponder from "../support/autoResponder.js";
import type * as support_triage from "../support/triage.js";
import type * as supportTickets from "../supportTickets.js";
import type * as tasks from "../tasks.js";
import type * as teamChat from "../teamChat.js";
import type * as teamChat_channels from "../teamChat/channels.js";
import type * as teamChat_departments from "../teamChat/departments.js";
import type * as teamChat_messages from "../teamChat/messages.js";
import type * as teamChat_threads from "../teamChat/threads.js";
import type * as teamGoals from "../teamGoals.js";
import type * as teamGoals_alignment from "../teamGoals/alignment.js";
import type * as teamGoals_okrs from "../teamGoals/okrs.js";
import type * as teamGoals_progress from "../teamGoals/progress.js";
import type * as teamOnboarding from "../teamOnboarding.js";
import type * as telemetry from "../telemetry.js";
import type * as templatePins from "../templatePins.js";
import type * as templatesData from "../templatesData.js";
import type * as users from "../users.js";
import type * as utils from "../utils.js";
import type * as vectors from "../vectors.js";
import type * as vendors from "../vendors.js";
import type * as voiceNotes from "../voiceNotes.js";
import type * as webhooks from "../webhooks.js";
import type * as webhooks_retry from "../webhooks/retry.js";
import type * as webhooksActions from "../webhooksActions.js";
import type * as whiteLabel_branding from "../whiteLabel/branding.js";
import type * as whiteLabel_domains from "../whiteLabel/domains.js";
import type * as whiteLabel_themes from "../whiteLabel/themes.js";
import type * as winsHistory from "../winsHistory.js";
import type * as workflowAssignments from "../workflowAssignments.js";
import type * as workflowHandoffs from "../workflowHandoffs.js";
import type * as workflowTemplates from "../workflowTemplates.js";
import type * as workflows from "../workflows.js";
import type * as workflows_crossDepartment from "../workflows/crossDepartment.js";
import type * as workflows_optimization from "../workflows/optimization.js";
import type * as workforce_capacity from "../workforce/capacity.js";
import type * as workforce_optimization from "../workforce/optimization.js";
import type * as workforce_skills from "../workforce/skills.js";
import type * as workforceAnalytics from "../workforceAnalytics.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  activity: typeof activity;
  activityFeed: typeof activityFeed;
  admin: typeof admin;
  adminAssistant: typeof adminAssistant;
  adminAuth: typeof adminAuth;
  adminAuthData: typeof adminAuthData;
  adminPasswordReset: typeof adminPasswordReset;
  adminPasswordResetData: typeof adminPasswordResetData;
  adminUsers: typeof adminUsers;
  adminUsersActions: typeof adminUsersActions;
  agentDatasets: typeof agentDatasets;
  agentMemory: typeof agentMemory;
  agentOrchestration: typeof agentOrchestration;
  agentOrchestrationData: typeof agentOrchestrationData;
  agentPerformance: typeof agentPerformance;
  "agentPerformance/costForecasting": typeof agentPerformance_costForecasting;
  "agentPerformance/predictive": typeof agentPerformance_predictive;
  agentProfile: typeof agentProfile;
  agentRouter: typeof agentRouter;
  aiAgents: typeof aiAgents;
  "analytics/capacity": typeof analytics_capacity;
  "analytics/churn": typeof analytics_churn;
  "analytics/cohorts": typeof analytics_cohorts;
  "analytics/funnel": typeof analytics_funnel;
  "analytics/ltv": typeof analytics_ltv;
  "analytics/optimization": typeof analytics_optimization;
  "analytics/predictiveROI": typeof analytics_predictiveROI;
  "analytics/retention": typeof analytics_retention;
  "analytics/teamVelocity": typeof analytics_teamVelocity;
  analyticsEngine: typeof analyticsEngine;
  apiSdk: typeof apiSdk;
  apiVersions: typeof apiVersions;
  approvalAnalytics: typeof approvalAnalytics;
  approvals: typeof approvals;
  audit: typeof audit;
  "audit/complianceReports": typeof audit_complianceReports;
  "audit/export": typeof audit_export;
  "audit/retention": typeof audit_retention;
  "audit/search": typeof audit_search;
  auditActions: typeof auditActions;
  auth: typeof auth;
  "auth/emailOtp": typeof auth_emailOtp;
  authCleanup: typeof authCleanup;
  billing: typeof billing;
  billingInternal: typeof billingInternal;
  brainDumps: typeof brainDumps;
  brandBuilder: typeof brandBuilder;
  branding: typeof branding;
  brands: typeof brands;
  businesses: typeof businesses;
  calendar: typeof calendar;
  "calendar/calendarIntegrations": typeof calendar_calendarIntegrations;
  "calendar/googleCalendar": typeof calendar_googleCalendar;
  "calendar/outlookCalendar": typeof calendar_outlookCalendar;
  "campaigns/mutations": typeof campaigns_mutations;
  "campaigns/orchestration": typeof campaigns_orchestration;
  "campaigns/templates": typeof campaigns_templates;
  capa: typeof capa;
  chunking: typeof chunking;
  complianceReports: typeof complianceReports;
  contacts: typeof contacts;
  contactsActions: typeof contactsActions;
  contentCapsules: typeof contentCapsules;
  contentCapsulesData: typeof contentCapsulesData;
  crisisManagement: typeof crisisManagement;
  crmIntegrations: typeof crmIntegrations;
  crmSync: typeof crmSync;
  cron: typeof cron;
  customApis: typeof customApis;
  "customApis/versioning": typeof customApis_versioning;
  customerJourney: typeof customerJourney;
  "customerJourney/analytics": typeof customerJourney_analytics;
  "customerJourney/stages": typeof customerJourney_stages;
  "customerJourney/triggers": typeof customerJourney_triggers;
  customerSegmentation: typeof customerSegmentation;
  "customerSegmentation/actions": typeof customerSegmentation_actions;
  "customerSegmentation/rules": typeof customerSegmentation_rules;
  "customerSegmentation/solopreneur": typeof customerSegmentation_solopreneur;
  customerSegmentationData: typeof customerSegmentationData;
  "data/agentCatalogSeed": typeof data_agentCatalogSeed;
  "data/playbooksSeed": typeof data_playbooksSeed;
  dataWarehouse: typeof dataWarehouse;
  "dataWarehouse/analytics": typeof dataWarehouse_analytics;
  "dataWarehouse/dataExports": typeof dataWarehouse_dataExports;
  "dataWarehouse/dataQuality": typeof dataWarehouse_dataQuality;
  "dataWarehouse/dataSources": typeof dataWarehouse_dataSources;
  "dataWarehouse/etlPipelines": typeof dataWarehouse_etlPipelines;
  "dataWarehouse/governance": typeof dataWarehouse_governance;
  "dataWarehouse/index": typeof dataWarehouse_index;
  "dataWarehouse/lineage": typeof dataWarehouse_lineage;
  "dataWarehouse/streaming": typeof dataWarehouse_streaming;
  demoVideos: typeof demoVideos;
  departmentBudgets: typeof departmentBudgets;
  "departmentBudgets/forecasting": typeof departmentBudgets_forecasting;
  "departmentBudgets/optimization": typeof departmentBudgets_optimization;
  departmentKpis: typeof departmentKpis;
  "departmentKpis/alerts": typeof departmentKpis_alerts;
  "departmentKpis/targets": typeof departmentKpis_targets;
  "departmentKpis/tracking": typeof departmentKpis_tracking;
  diagnostics: typeof diagnostics;
  docProcessing: typeof docProcessing;
  docs: typeof docs;
  docsFaqs: typeof docsFaqs;
  docsInternal: typeof docsInternal;
  docsVideos: typeof docsVideos;
  emailAnalytics: typeof emailAnalytics;
  emailConfig: typeof emailConfig;
  emailDraftAgent: typeof emailDraftAgent;
  emailDraftAgentData: typeof emailDraftAgentData;
  emailDrafts: typeof emailDrafts;
  emailTracking: typeof emailTracking;
  emails: typeof emails;
  emailsActions: typeof emailsActions;
  enableFeatures: typeof enableFeatures;
  enterpriseMetrics: typeof enterpriseMetrics;
  enterpriseSecurity: typeof enterpriseSecurity;
  enterpriseSupport: typeof enterpriseSupport;
  entitlements: typeof entitlements;
  evals: typeof evals;
  evalsInternal: typeof evalsInternal;
  experiments: typeof experiments;
  experimentsActions: typeof experimentsActions;
  featureFlags: typeof featureFlags;
  files: typeof files;
  governance: typeof governance;
  "governance/autoEnforcement": typeof governance_autoEnforcement;
  "governance/remediation": typeof governance_remediation;
  "governance/violations": typeof governance_violations;
  governanceAutomation: typeof governanceAutomation;
  governanceRules: typeof governanceRules;
  health: typeof health;
  "helpCoach/assistant": typeof helpCoach_assistant;
  "helpCoach/tutorials": typeof helpCoach_tutorials;
  http: typeof http;
  init: typeof init;
  initWorkspaceDefaults: typeof initWorkspaceDefaults;
  initiativeJourney: typeof initiativeJourney;
  initiatives: typeof initiatives;
  inspector: typeof inspector;
  integrationPlatform: typeof integrationPlatform;
  "integrationPlatform/billing": typeof integrationPlatform_billing;
  "integrationPlatform/costs": typeof integrationPlatform_costs;
  invoices: typeof invoices;
  invoicesActions: typeof invoicesActions;
  kgraph: typeof kgraph;
  kms: typeof kms;
  kmsActions: typeof kmsActions;
  knowledge: typeof knowledge;
  kpis: typeof kpis;
  landingChat: typeof landingChat;
  learningContent: typeof learningContent;
  learningContentActions: typeof learningContentActions;
  "lib/aiAgents/admin": typeof lib_aiAgents_admin;
  "lib/aiAgents/config": typeof lib_aiAgents_config;
  "lib/aiAgents/datasets": typeof lib_aiAgents_datasets;
  "lib/aiAgents/publish": typeof lib_aiAgents_publish;
  "lib/aiAgents/training": typeof lib_aiAgents_training;
  "lib/aiAgents/versions": typeof lib_aiAgents_versions;
  "lib/errors": typeof lib_errors;
  "locations/analytics": typeof locations_analytics;
  "locations/compliance": typeof locations_compliance;
  "locations/management": typeof locations_management;
  notifications: typeof notifications;
  "notifications/realtime": typeof notifications_realtime;
  nudges: typeof nudges;
  oidc: typeof oidc;
  oidcActions: typeof oidcActions;
  onboarding: typeof onboarding;
  openai: typeof openai;
  openapi: typeof openapi;
  passwordAuth: typeof passwordAuth;
  passwordAuthActions: typeof passwordAuthActions;
  passwordAuthData: typeof passwordAuthData;
  "payments/paypal": typeof payments_paypal;
  "payments/stripe": typeof payments_stripe;
  playbookExecutions: typeof playbookExecutions;
  playbookVersions: typeof playbookVersions;
  playbooks: typeof playbooks;
  policyManagement: typeof policyManagement;
  portfolioManagement: typeof portfolioManagement;
  "portfolioManagement/analytics": typeof portfolioManagement_analytics;
  "portfolioManagement/optimization": typeof portfolioManagement_optimization;
  "portfolioManagement/predictive": typeof portfolioManagement_predictive;
  rateLimiting: typeof rateLimiting;
  "resources/allocation": typeof resources_allocation;
  "resources/optimization": typeof resources_optimization;
  revenueAttribution: typeof revenueAttribution;
  "risk/mitigation": typeof risk_mitigation;
  "risk/reporting": typeof risk_reporting;
  "risk/scenarios": typeof risk_scenarios;
  riskAnalytics: typeof riskAnalytics;
  roiCalculations: typeof roiCalculations;
  "sales/activities": typeof sales_activities;
  "sales/forecasting": typeof sales_forecasting;
  "sales/pipeline": typeof sales_pipeline;
  saml: typeof saml;
  samlActions: typeof samlActions;
  schedule: typeof schedule;
  "scheduling/assistant": typeof scheduling_assistant;
  "scheduling/availability": typeof scheduling_availability;
  "schema/activity": typeof schema_activity;
  "schema/admin": typeof schema_admin;
  "schema/agents": typeof schema_agents;
  "schema/calendar": typeof schema_calendar;
  "schema/contacts": typeof schema_contacts;
  "schema/content": typeof schema_content;
  "schema/core": typeof schema_core;
  "schema/demoVideos": typeof schema_demoVideos;
  "schema/docs": typeof schema_docs;
  "schema/email": typeof schema_email;
  "schema/enterprise": typeof schema_enterprise;
  "schema/index": typeof schema_index;
  "schema/initiatives": typeof schema_initiatives;
  "schema/integrations": typeof schema_integrations;
  "schema/kpi": typeof schema_kpi;
  "schema/onboarding": typeof schema_onboarding;
  "schema/orchestration": typeof schema_orchestration;
  "schema/risk": typeof schema_risk;
  "schema/security": typeof schema_security;
  "schema/social": typeof schema_social;
  "schema/support": typeof schema_support;
  "schema/team": typeof schema_team;
  "schema/testing": typeof schema_testing;
  "schema/vectors": typeof schema_vectors;
  "schema/whiteLabel": typeof schema_whiteLabel;
  "schema/wins": typeof schema_wins;
  "schema/workflows": typeof schema_workflows;
  scim: typeof scim;
  search: typeof search;
  "security/compliance": typeof security_compliance;
  "security/incidents": typeof security_incidents;
  "security/threats": typeof security_threats;
  seed: typeof seed;
  setupWizard: typeof setupWizard;
  setupWizardData: typeof setupWizardData;
  socialAnalytics: typeof socialAnalytics;
  socialAnalyticsAdvanced: typeof socialAnalyticsAdvanced;
  "socialAnalyticsAdvanced/crisis": typeof socialAnalyticsAdvanced_crisis;
  "socialAnalyticsAdvanced/listening": typeof socialAnalyticsAdvanced_listening;
  "socialAnalyticsAdvanced/responses": typeof socialAnalyticsAdvanced_responses;
  socialApiConfigs: typeof socialApiConfigs;
  socialContentAgent: typeof socialContentAgent;
  "socialContentAgent/analytics": typeof socialContentAgent_analytics;
  "socialContentAgent/optimization": typeof socialContentAgent_optimization;
  socialIntegrations: typeof socialIntegrations;
  "socialIntegrations/oauth": typeof socialIntegrations_oauth;
  "socialIntegrations/webhooks": typeof socialIntegrations_webhooks;
  socialIntegrationsActions: typeof socialIntegrationsActions;
  socialMediaDocs: typeof socialMediaDocs;
  socialPosts: typeof socialPosts;
  socialPostsCron: typeof socialPostsCron;
  solopreneur: typeof solopreneur;
  strategicInitiatives: typeof strategicInitiatives;
  "support/autoResponder": typeof support_autoResponder;
  "support/triage": typeof support_triage;
  supportTickets: typeof supportTickets;
  tasks: typeof tasks;
  teamChat: typeof teamChat;
  "teamChat/channels": typeof teamChat_channels;
  "teamChat/departments": typeof teamChat_departments;
  "teamChat/messages": typeof teamChat_messages;
  "teamChat/threads": typeof teamChat_threads;
  teamGoals: typeof teamGoals;
  "teamGoals/alignment": typeof teamGoals_alignment;
  "teamGoals/okrs": typeof teamGoals_okrs;
  "teamGoals/progress": typeof teamGoals_progress;
  teamOnboarding: typeof teamOnboarding;
  telemetry: typeof telemetry;
  templatePins: typeof templatePins;
  templatesData: typeof templatesData;
  users: typeof users;
  utils: typeof utils;
  vectors: typeof vectors;
  vendors: typeof vendors;
  voiceNotes: typeof voiceNotes;
  webhooks: typeof webhooks;
  "webhooks/retry": typeof webhooks_retry;
  webhooksActions: typeof webhooksActions;
  "whiteLabel/branding": typeof whiteLabel_branding;
  "whiteLabel/domains": typeof whiteLabel_domains;
  "whiteLabel/themes": typeof whiteLabel_themes;
  winsHistory: typeof winsHistory;
  workflowAssignments: typeof workflowAssignments;
  workflowHandoffs: typeof workflowHandoffs;
  workflowTemplates: typeof workflowTemplates;
  workflows: typeof workflows;
  "workflows/crossDepartment": typeof workflows_crossDepartment;
  "workflows/optimization": typeof workflows_optimization;
  "workforce/capacity": typeof workforce_capacity;
  "workforce/optimization": typeof workforce_optimization;
  "workforce/skills": typeof workforce_skills;
  workforceAnalytics: typeof workforceAnalytics;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
