-- Migration: 0041_enrich_solopreneur_journeys.sql
-- Enrich all 40 solopreneur user journeys with descriptions, stages, KPIs, workflow mapping, outcomes_prompt.

BEGIN;

UPDATE user_journeys SET title = 'Networking Event Calendar' WHERE persona = 'solopreneur' AND title = 'Networking Event Caldendar';

-- 5-phase stages (aligned with initiative framework)
-- We update description, stages, kpis, primary_workflow_template_name, suggested_workflows, outcomes_prompt, category per journey.

UPDATE user_journeys SET description = 'Land your first paying client: define your offer, identify ideal clients, and run targeted outreach until you close.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Number of qualified leads","Meetings booked","Proposals sent","First client closed"]'::jsonb, primary_workflow_template_name = 'Lead Generation Workflow', suggested_workflows = '["Outbound Prospecting","Deal Closing"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 1 paying client in 90 days). Any timeline?', category = 'sales' WHERE persona = 'solopreneur' AND title = 'First Client Acquisition';

UPDATE user_journeys SET description = 'Set up professional invoicing: choose a tool, create templates, and automate reminders so you get paid on time.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Invoices sent on time","Average days to payment","Overdue invoices"]'::jsonb, primary_workflow_template_name = 'Vendor Onboarding', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. all invoices within 24h of project end). Timeline?', category = 'operations' WHERE persona = 'solopreneur' AND title = 'Automated Invoicing Setup';

UPDATE user_journeys SET description = 'Establish yourself as a thought leader: define your voice, choose platforms, and publish consistently to grow influence.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Followers/connections","Engagement rate","Website traffic","Inbound opportunities"]'::jsonb, primary_workflow_template_name = 'Social Media Campaign Workflow', suggested_workflows = '["Content Creation Workflow","Initiative Framework"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 1K followers in 6 months). Timeline?', category = 'marketing' WHERE persona = 'solopreneur' AND title = 'Personal Brand Building';

UPDATE user_journeys SET description = 'Launch a professional portfolio site: plan structure, create content, and go live so clients can find and trust you.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Pages published","Monthly visitors","Contact form submissions","Time to launch"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Product Launch Campaign","SEO Optimization Audit"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. live in 4 weeks, 3 case studies). Timeline?', category = 'marketing' WHERE persona = 'solopreneur' AND title = 'Portfolio Website Launch';

UPDATE user_journeys SET description = 'Build a repeatable content strategy: define pillars, plan a calendar, and create and schedule posts that attract your audience.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Posts per week","Engagement rate","Follower growth","Content themes covered"]'::jsonb, primary_workflow_template_name = 'Social Media Campaign Workflow', suggested_workflows = '["Social Media Calendar","Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 3 posts/week, 5% engagement). Which platforms? Timeline?', category = 'marketing' WHERE persona = 'solopreneur' AND title = 'Social Media Content Strategy';

UPDATE user_journeys SET description = 'Automate how new clients get started: welcome sequence, contracts, and first deliverables so onboarding is smooth and scalable.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Time to first deliverable","Client satisfaction score","Onboarding tasks completed"]'::jsonb, primary_workflow_template_name = 'Customer Onboarding', suggested_workflows = '["Vendor Onboarding","Email Nurture Sequence"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. new client productive within 5 days). Timeline?', category = 'operations' WHERE persona = 'solopreneur' AND title = 'Client Onboarding Automation';

UPDATE user_journeys SET description = 'Get expenses under control: choose a system, categorize transactions, and review regularly for tax and profitability.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Expenses categorized monthly","Tax-ready reports","Time spent on bookkeeping"]'::jsonb, primary_workflow_template_name = 'Pipeline Review', suggested_workflows = '["Financial Reporting","Budget Planning"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. all expenses categorized weekly). Timeline?', category = 'finance' WHERE persona = 'solopreneur' AND title = 'Expense Tracking Setup';

UPDATE user_journeys SET description = 'Stay tax-ready quarter by quarter: track income and expenses, set aside estimated tax, and prepare filings on time.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Estimated tax set aside","Quarterly filings on time","Audit-ready records"]'::jsonb, primary_workflow_template_name = 'Tax Filing Prep', suggested_workflows = '["Financial Reporting","Budget Planning"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. no surprises at year-end). Timeline?', category = 'finance' WHERE persona = 'solopreneur' AND title = 'Quarterly Tax Prep';

UPDATE user_journeys SET description = 'Price your services with confidence: research market rates, model packages, and test pricing until you find the right fit.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Win rate at new price","Average project value","Pricing page conversion"]'::jsonb, primary_workflow_template_name = 'Competitor Analysis Workflow', suggested_workflows = '["Strategic Planning Cycle","Win/Loss Analysis"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 20% rate increase with same close rate). Timeline?', category = 'sales' WHERE persona = 'solopreneur' AND title = 'Service Pricing Strategy';

UPDATE user_journeys SET description = 'Hire your first VA: define tasks, write a brief, screen candidates, and onboard so you can delegate reliably.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Hours delegated per week","Tasks offloaded","VA retention"]'::jsonb, primary_workflow_template_name = 'Recruitment Pipeline', suggested_workflows = '["Employee Onboarding","Vendor Onboarding"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 10 hrs/week delegated in 60 days). Timeline?', category = 'operations' WHERE persona = 'solopreneur' AND title = 'Virtual Assistant Hiring';

UPDATE user_journeys SET description = 'Run effective cold email: build a list, write sequences, and follow up until you get replies and meetings.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Emails sent","Open rate","Reply rate","Meetings booked"]'::jsonb, primary_workflow_template_name = 'Outbound Prospecting', suggested_workflows = '["Lead Generation Workflow","Email Nurture Sequence"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 5% reply rate, 2 meetings/week). Timeline?', category = 'sales' WHERE persona = 'solopreneur' AND title = 'Cold Email Outreach';

UPDATE user_journeys SET description = 'Grow your network on LinkedIn: optimize profile, post consistently, and engage so opportunities find you.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Connections per month","Post impressions","Inbound DMs","Profile views"]'::jsonb, primary_workflow_template_name = 'Social Media Calendar', suggested_workflows = '["Influencer Outreach","Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 500 connections in 90 days). Timeline?', category = 'marketing' WHERE persona = 'solopreneur' AND title = 'LinkedIn Networking';

UPDATE user_journeys SET description = 'Get found locally: claim and optimize your Google Business Profile so you show up in search and maps.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Profile completeness","Search impressions","Actions (calls, website clicks)","Reviews"]'::jsonb, primary_workflow_template_name = 'SEO Optimization Audit', suggested_workflows = '["Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. in top 3 for 2 keywords, 10 reviews). Timeline?', category = 'marketing' WHERE persona = 'solopreneur' AND title = 'Google Business Profile Optimization';

UPDATE user_journeys SET description = 'Run projects without chaos: pick a tool, define workflows, and track tasks and deadlines so nothing falls through the cracks.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Projects on time","Tasks completed","Time spent on PM admin"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Roadmap Planning"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. all client projects in one place). Timeline?', category = 'operations' WHERE persona = 'solopreneur' AND title = 'Project Management Setup';

UPDATE user_journeys SET description = 'Create a winning proposal template: structure, copy, and pricing so you can send professional proposals in minutes.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Time to send proposal","Win rate","Proposals sent per month"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Deal Closing"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. proposal out within 24h of discovery). Timeline?', category = 'sales' WHERE persona = 'solopreneur' AND title = 'Proposal Template Creation';

UPDATE user_journeys SET description = 'Protect yourself with solid contracts: draft or adapt terms, get legal review if needed, and use the same template for every client.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Contracts signed","Disputes avoided","Time to signature"]'::jsonb, primary_workflow_template_name = 'Contract Review', suggested_workflows = '["Content Creation Workflow","Deal Closing"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. one master contract, signed within 1 week). Timeline?', category = 'legal' WHERE persona = 'solopreneur' AND title = 'Contract Template Creation';

UPDATE user_journeys SET description = 'Listen to clients systematically: choose when and how to ask for feedback, collect it, and act on it to improve retention.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Feedback responses","NPS or CSAT score","Actions taken from feedback"]'::jsonb, primary_workflow_template_name = 'Win/Loss Analysis', suggested_workflows = '["Churn Prevention","Account Renewal"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. NPS 40+, feedback after every project). Timeline?', category = 'support' WHERE persona = 'solopreneur' AND title = 'Customer Feedback Loop';

UPDATE user_journeys SET description = 'Grow an email list you own: add signup forms, create a lead magnet, and nurture subscribers into clients.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Subscribers","Open rate","Click rate","Conversions from list"]'::jsonb, primary_workflow_template_name = 'Email Nurture Sequence', suggested_workflows = '["Lead Generation Workflow","Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 500 subscribers in 6 months, 2% click rate). Timeline?', category = 'marketing' WHERE persona = 'solopreneur' AND title = 'Email List Building';

UPDATE user_journeys SET description = 'Run webinars that convert: pick a topic, build registration and follow-up emails, and host live or evergreen.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Registrations","Attendance rate","Conversions (signup or sale)"]'::jsonb, primary_workflow_template_name = 'Webinar Hosting', suggested_workflows = '["Email Nurture Sequence","Product Launch Campaign"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. first webinar in 30 days, 50 attendees). Timeline?', category = 'marketing' WHERE persona = 'solopreneur' AND title = 'Webinar Funnel Setup';

UPDATE user_journeys SET description = 'Create and launch a profitable online course: validate the idea, build the curriculum, and sell to your audience.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Students enrolled","Completion rate","Revenue","Satisfaction score"]'::jsonb, primary_workflow_template_name = 'Initiative Framework', suggested_workflows = '["Content Creation Workflow","Email Sequence Workflow","Lead Generation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 50 students in first cohort, 80% completion). Timeline?', category = 'product' WHERE persona = 'solopreneur' AND title = 'Online Course Launch';

UPDATE user_journeys SET description = 'Launch an affiliate or referral program: define commission, recruit partners, and track payouts to grow through others.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Affiliates recruited","Revenue from affiliates","Payout accuracy"]'::jsonb, primary_workflow_template_name = 'Vendor Onboarding', suggested_workflows = '["Partnership Development","Upsell Campaign"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 10 active affiliates). Timeline?', category = 'sales' WHERE persona = 'solopreneur' AND title = 'Affiliate Program Setup';

UPDATE user_journeys SET description = 'Launch a professional podcast: niche, format, and first 10 episodes from concept to distribution.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Episodes published","Downloads per episode","Subscriber count","Listener retention"]'::jsonb, primary_workflow_template_name = 'Initiative Framework', suggested_workflows = '["Content Creation Workflow","Social Media Campaign Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 10 episodes live, 1K downloads/episode). Timeline?', category = 'content' WHERE persona = 'solopreneur' AND title = 'Podcast Launch';

UPDATE user_journeys SET description = 'Build a traffic-generating blog: define pillars, plan a calendar, and publish SEO-optimized content consistently.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Posts published per month","Organic traffic","Email signups from content","Domain authority"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Social Media Calendar","SEO Optimization Audit"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 4 posts/month, 5K organic visits in 6 months). Timeline?', category = 'content' WHERE persona = 'solopreneur' AND title = 'Blog Content Calendar';

UPDATE user_journeys SET description = 'Get found on search: audit your site, fix basics (titles, meta, structure), and track rankings.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Keywords tracked","Organic traffic","Backlinks","Core Web Vitals"]'::jsonb, primary_workflow_template_name = 'SEO Optimization Audit', suggested_workflows = '["Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. top 10 for 5 keywords). Timeline?', category = 'marketing' WHERE persona = 'solopreneur' AND title = 'SEO Basic Setup';

UPDATE user_journeys SET description = 'Design a sustainable schedule: block time for deep work, client delivery, and admin so you hit goals without burnout.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Hours deep work per week","Tasks completed on time","Work-life balance score"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '[]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 20 hrs deep work/week). Timeline?', category = 'operations' WHERE persona = 'solopreneur' AND title = 'Time Blocking Schedule';

UPDATE user_journeys SET description = 'Create a productive home office: ergonomics, tech, and boundaries so you work effectively from anywhere.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Setup completion","Productivity self-rating","Reliability (uptime, connectivity)"]'::jsonb, primary_workflow_template_name = 'Office Move/Expansion', suggested_workflows = '["IT Asset Provisioning"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. dedicated workspace, no tech issues on calls). Timeline?', category = 'operations' WHERE persona = 'solopreneur' AND title = 'Remote Office Setup';

UPDATE user_journeys SET description = 'Find the right health coverage: compare options for self-employed, understand costs, and enroll before the deadline.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Plans compared","Enrollment completed","Monthly premium and out-of-pocket"]'::jsonb, primary_workflow_template_name = 'Benefits Enrollment', suggested_workflows = '["Vendor Onboarding"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. coverage by open enrollment end). Timeline?', category = 'operations' WHERE persona = 'solopreneur' AND title = 'Health Insurance Research';

UPDATE user_journeys SET description = 'Protect your business with liability insurance: assess risk, compare policies, and get covered.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Policies compared","Coverage in place","Annual premium"]'::jsonb, primary_workflow_template_name = 'Vendor Onboarding', suggested_workflows = '[]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. E&O and general liability in place). Timeline?', category = 'operations' WHERE persona = 'solopreneur' AND title = 'Liability Insurance Setup';

UPDATE user_journeys SET description = 'Separate business and personal finances: open a business account, move transactions, and keep books clean.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Business account opened","% transactions through business account","Reconciliation time"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Budget Planning","Financial Reporting"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 100% business income/expense in business account). Timeline?', category = 'finance' WHERE persona = 'solopreneur' AND title = 'Bank Account Separation';

UPDATE user_journeys SET description = 'Build a safety net: decide how much to keep in reserve, set up automatic savings, and hit your target.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Months of expenses saved","Auto-transfer amount","Target date met"]'::jsonb, primary_workflow_template_name = 'Cash Flow Management', suggested_workflows = '["Budget Planning"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 6 months expenses in 12 months). Timeline?', category = 'finance' WHERE persona = 'solopreneur' AND title = 'Emergency Fund Planning';

UPDATE user_journeys SET description = 'Start saving for retirement as a solopreneur: choose a SEP-IRA or solo 401(k), open the account, and contribute regularly.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Account opened","Monthly/annual contribution","Target % of income saved"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Budget Planning","Financial Reporting"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 15% of income to retirement). Timeline?', category = 'finance' WHERE persona = 'solopreneur' AND title = 'Retirement Saving Setup';

UPDATE user_journeys SET description = 'Plan and attend networking that matters: pick events, set a cadence, and follow up so relationships turn into opportunities.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Events per month","New connections","Follow-ups sent","Opportunities generated"]'::jsonb, primary_workflow_template_name = 'Social Media Calendar', suggested_workflows = '["Content Creation Workflow","Lead Generation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 2 events/month, 5 meaningful follow-ups each). Timeline?', category = 'marketing' WHERE persona = 'solopreneur' AND title = 'Networking Event Calendar';

UPDATE user_journeys SET description = 'Strengthen client relationships with thoughtful gifts: set a budget, choose occasions, and send consistently.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Gifts sent per quarter","Client satisfaction","Referrals attributed"]'::jsonb, primary_workflow_template_name = 'Account Renewal', suggested_workflows = '["Churn Prevention"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. gift at project end plus holidays). Timeline?', category = 'support' WHERE persona = 'solopreneur' AND title = 'Client Gift Strategy';

UPDATE user_journeys SET description = 'Get more and better reviews: ask at the right time, make it easy to leave feedback, and respond to build trust.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Reviews received","Average rating","Response rate and time"]'::jsonb, primary_workflow_template_name = 'Win/Loss Analysis', suggested_workflows = '["Account Renewal"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 10 Google reviews, 4.8+ average). Timeline?', category = 'marketing' WHERE persona = 'solopreneur' AND title = 'Review Management';

UPDATE user_journeys SET description = 'Grow revenue from existing clients: identify add-ons or next projects, time the ask, and close without pressure.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Upsell rate","Revenue from existing clients","Proposals accepted"]'::jsonb, primary_workflow_template_name = 'Upsell Campaign', suggested_workflows = '["Account Renewal","Deal Closing"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 30% of clients buy add-on within 6 months). Timeline?', category = 'sales' WHERE persona = 'solopreneur' AND title = 'Upsell Strategy';

UPDATE user_journeys SET description = 'Move long-term clients to new terms or systems: communicate changes, update contracts, and retain them through the transition.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Clients migrated","Retention rate","Time to complete migration"]'::jsonb, primary_workflow_template_name = 'Account Renewal', suggested_workflows = '["Churn Prevention","Contract Review"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. all legacy clients on new terms, 95% retained). Timeline?', category = 'support' WHERE persona = 'solopreneur' AND title = 'Legacy Client Migration';

UPDATE user_journeys SET description = 'Choose and set up the right tools: task management, calendar, and communication so you spend less time switching.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Tools in use","Time saved per week","Adoption (tasks in system)"]'::jsonb, primary_workflow_template_name = 'IT Asset Provisioning', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. one source of truth for tasks and calendar). Timeline?', category = 'operations' WHERE persona = 'solopreneur' AND title = 'Productivity Tool Stack';

UPDATE user_journeys SET description = 'Never lose critical files: identify what to back up, choose a solution, and automate so backups run without thinking.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Systems backed up","Backup frequency","Test restore success"]'::jsonb, primary_workflow_template_name = 'IT Asset Provisioning', suggested_workflows = '["Quality Assurance Audit"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. daily automated backup, 1 test restore per quarter). Timeline?', category = 'operations' WHERE persona = 'solopreneur' AND title = 'Data Backup Strategy';

UPDATE user_journeys SET description = 'Secure and simplify logins: adopt a password manager, migrate key accounts, and use strong unique passwords everywhere.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Accounts in manager","Strong passwords %","No reused passwords"]'::jsonb, primary_workflow_template_name = 'IT Asset Provisioning', suggested_workflows = '[]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. all business logins in one manager, 2FA where available). Timeline?', category = 'operations' WHERE persona = 'solopreneur' AND title = 'Password Management';

UPDATE user_journeys SET description = 'Define how you sound everywhere: tone, vocabulary, and examples so your content and outreach feel consistently you.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Guide documented","Content aligned to voice","Consistency score (self or audit)"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Social Media Campaign Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. one-page voice guide, used for all new content). Timeline?', category = 'marketing' WHERE persona = 'solopreneur' AND title = 'Brand Voice Guide';

COMMIT;
