-- Migration: 0042_enrich_startup_journeys.sql
-- Enrich all 40 startup user journeys with descriptions, stages, KPIs, workflow mapping, outcomes_prompt.

BEGIN;

-- 5-phase stages (aligned with initiative framework)
-- Each journey gets: description, stages, kpis, primary_workflow_template_name, suggested_workflows, outcomes_prompt, category

UPDATE user_journeys SET description = 'Raise your first institutional round: prepare materials, build an investor list, run the process, and close the round.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Pitch deck ready","Investor meetings","Term sheets","Amount closed"]'::jsonb, primary_workflow_template_name = 'Fundraising Round', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. close $X by date). Any timeline or milestones?', category = 'strategy' WHERE persona = 'startup' AND title = 'Seed Fundraising';

UPDATE user_journeys SET description = 'Ship your minimum viable product: scope features, build, test with users, and launch to the market.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["MVP scope defined","Beta users","Launch date","Early adoption"]'::jsonb, primary_workflow_template_name = 'Product Launch Workflow', suggested_workflows = '["Initiative Framework"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 100 users in 30 days). Timeline?', category = 'product' WHERE persona = 'startup' AND title = 'MVP Launch';

UPDATE user_journeys SET description = 'Hire your first 10 team members: define roles, source candidates, run process, and onboard effectively.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Roles defined","Candidates in pipeline","Offers accepted","Time to hire"]'::jsonb, primary_workflow_template_name = 'Recruitment Pipeline', suggested_workflows = '["Employee Onboarding"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 10 hires in 6 months). Which roles first? Timeline?', category = 'hr' WHERE persona = 'startup' AND title = 'First 10 Hires';

UPDATE user_journeys SET description = 'Formalize the co-founder relationship: align on equity, roles, and expectations with a clear agreement.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Agreement drafted","Legal review","Signed","Vesting in place"]'::jsonb, primary_workflow_template_name = 'Contract Review', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. signed agreement, clear equity split). Timeline?', category = 'legal' WHERE persona = 'startup' AND title = 'Co-founder Agreement';

UPDATE user_journeys SET description = 'Incorporate your company: choose entity type, jurisdiction, and complete formation and filings.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Entity type chosen","Formation filed","EIN and bank account","Compliance in place"]'::jsonb, primary_workflow_template_name = 'Contract Review', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. Delaware C-corp in 2 weeks). Timeline?', category = 'legal' WHERE persona = 'startup' AND title = 'Entity Incorporation';

UPDATE user_journeys SET description = 'Set up and maintain your cap table: issue founder equity, document options, and keep it accurate for investors.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Cap table tool","Founder equity recorded","Option pool defined","Investor-ready"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Budget Planning","Financial Reporting"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. clean cap table for due diligence). Timeline?', category = 'finance' WHERE persona = 'startup' AND title = 'Cap Table Setup';

UPDATE user_journeys SET description = 'Validate that you are building something people want: talk to users, measure fit, and iterate until it clicks.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Interviews conducted","Retention/usage metrics","PMF score","Pivot or persevere decision"]'::jsonb, primary_workflow_template_name = 'Initiative Framework', suggested_workflows = '["Competitor Analysis Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 40% very disappointed if product gone). Timeline?', category = 'strategy' WHERE persona = 'startup' AND title = 'Product Market Fit Validation';

UPDATE user_journeys SET description = 'Recruit and onboard beta users: define criteria, find them, and run a structured beta program.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Beta criteria defined","Users recruited","Active usage","Feedback collected"]'::jsonb, primary_workflow_template_name = 'Lead Generation Workflow', suggested_workflows = '["Outbound Prospecting"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 50 active beta users). Timeline?', category = 'sales' WHERE persona = 'startup' AND title = 'Beta User Recruitment';

UPDATE user_journeys SET description = 'Grow a waitlist before launch: landing page, signup flow, and nurture until you open the product.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Waitlist size","Signup conversion","Email engagement","Launch day activation"]'::jsonb, primary_workflow_template_name = 'Email Nurture Sequence', suggested_workflows = '["Lead Generation Workflow","Social Media Campaign Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 1K waitlist before launch). Timeline?', category = 'marketing' WHERE persona = 'startup' AND title = 'Waitlist Growth Strategy';

UPDATE user_journeys SET description = 'Create a repeatable investor update: metrics, narrative, and asks so investors stay informed and engaged.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Update cadence","Open rate","Follow-up meetings","Sent on time"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. monthly update, 80% open rate). Timeline?', category = 'strategy' WHERE persona = 'startup' AND title = 'Investor Update Template';

UPDATE user_journeys SET description = 'Prepare and run effective board meetings: deck, metrics, and decisions so the board adds value.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Deck sent on time","Decisions documented","Action items tracked","Board satisfaction"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. quarterly meetings, clear outcomes). Timeline?', category = 'strategy' WHERE persona = 'startup' AND title = 'Board Meeting Deck';

UPDATE user_journeys SET description = 'Iterate on your pitch deck: story, slides, and feedback until it resonates with investors.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Deck version","Meetings from deck","Conversion to next step","Time to next iteration"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 10 investor meetings from deck). Timeline?', category = 'strategy' WHERE persona = 'startup' AND title = 'Pitch Deck Iteration';

UPDATE user_journeys SET description = 'Design and implement an employee stock option plan: size pool, terms, and legal setup.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Pool size","Plan documents","Grants issued","Employee understanding"]'::jsonb, primary_workflow_template_name = 'Contract Review', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 10% option pool, plan approved). Timeline?', category = 'hr' WHERE persona = 'startup' AND title = 'Employee Stock Option Plan';

UPDATE user_journeys SET description = 'Build a strong remote or hybrid team culture: norms, rituals, and tools so everyone stays aligned.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Norms documented","Meeting cadence","Engagement score","Retention"]'::jsonb, primary_workflow_template_name = 'Employee Onboarding', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. async-first, weekly all-hands). Timeline?', category = 'hr' WHERE persona = 'startup' AND title = 'Remote Team Culture';

UPDATE user_journeys SET description = 'Set up agile workflows: sprints, standups, and backlog so the team ships predictably.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Sprint velocity","Cycle time","Retro actions","Delivery on commit"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Roadmap Planning"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 2-week sprints, predictable delivery). Timeline?', category = 'operations' WHERE persona = 'startup' AND title = 'Agile Workflow Setup';

UPDATE user_journeys SET description = 'Implement CI/CD: build, test, and deploy automatically so releases are fast and safe.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Build time","Deploy frequency","Failed deploy rate","Time to rollback"]'::jsonb, primary_workflow_template_name = 'Feature Development', suggested_workflows = '["Roadmap Planning"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. deploy on every merge). Timeline?', category = 'operations' WHERE persona = 'startup' AND title = 'CI/CD Pipeline Setup';

UPDATE user_journeys SET description = 'Prepare for SOC 2 or similar security compliance: scope, controls, and evidence for audit readiness.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Scope defined","Controls implemented","Evidence collected","Audit passed"]'::jsonb, primary_workflow_template_name = 'GDPR Compliance Audit', suggested_workflows = '["Policy Update"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. SOC 2 Type I in 12 months). Timeline?', category = 'operations' WHERE persona = 'startup' AND title = 'Security Compliance (SOC2 Prep)';

UPDATE user_journeys SET description = 'Publish and maintain a clear data privacy policy: what you collect, how you use it, and user rights.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Policy published","Review cycle","User consent flow","Compliant with regulations"]'::jsonb, primary_workflow_template_name = 'Policy Update', suggested_workflows = '["Contract Review"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. GDPR/CCPA aligned). Timeline?', category = 'legal' WHERE persona = 'startup' AND title = 'Data Privacy Policy';

UPDATE user_journeys SET description = 'Draft and publish terms of service: scope, liability, and acceptance so the product is legally covered.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["ToS drafted","Legal review","Published","Acceptance tracked"]'::jsonb, primary_workflow_template_name = 'Contract Review', suggested_workflows = '["Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. live before launch). Timeline?', category = 'legal' WHERE persona = 'startup' AND title = 'Terms of Service Draft';

UPDATE user_journeys SET description = 'Register your trademark: search, file, and maintain protection for your brand.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Search done","Application filed","Registration","Renewals"]'::jsonb, primary_workflow_template_name = 'IP Filing', suggested_workflows = '["Contract Review"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. registered in key markets). Timeline?', category = 'legal' WHERE persona = 'startup' AND title = 'Trademark Registration';

UPDATE user_journeys SET description = 'Understand your competitive landscape: who they are, what they do, and where you can win.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Competitors mapped","SWOT per competitor","Differentiation clear","Updated quarterly"]'::jsonb, primary_workflow_template_name = 'Competitor Analysis Workflow', suggested_workflows = '["Initiative Framework"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. top 5 competitors profiled). Timeline?', category = 'strategy' WHERE persona = 'startup' AND title = 'Competitor Analysis';

UPDATE user_journeys SET description = 'Model and track unit economics: LTV, CAC, contribution margin, and path to profitability.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["LTV/CAC ratio","Contribution margin","Payback period","Model updated monthly"]'::jsonb, primary_workflow_template_name = 'Financial Reporting', suggested_workflows = '["Budget Planning","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. positive contribution per unit). Timeline?', category = 'finance' WHERE persona = 'startup' AND title = 'Unit Economics Analysis';

UPDATE user_journeys SET description = 'Monitor and manage burn rate: track spend, runway, and levers to extend or reduce burn.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Monthly burn","Runway in months","Budget vs actual","Forecast accuracy"]'::jsonb, primary_workflow_template_name = 'Financial Reporting', suggested_workflows = '["Budget Planning","Pipeline Review"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 18 months runway). Timeline?', category = 'finance' WHERE persona = 'startup' AND title = 'Burn Rate Monitoring';

UPDATE user_journeys SET description = 'Extend runway without raising: cut costs, improve efficiency, or add revenue to buy time.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Runway before/after","Cost reductions","Revenue initiatives","Months gained"]'::jsonb, primary_workflow_template_name = 'Fundraising Round', suggested_workflows = '["Budget Planning","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 6 more months runway). Timeline?', category = 'finance' WHERE persona = 'startup' AND title = 'Runway Extension Strategy';

UPDATE user_journeys SET description = 'Run growth experiments: hypothesis, test, measure, and scale what works.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Experiments run","Win rate","Impact on key metric","Learning documented"]'::jsonb, primary_workflow_template_name = 'A/B Testing Workflow', suggested_workflows = '["Social Media Campaign Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 2 experiments per month). Timeline?', category = 'marketing' WHERE persona = 'startup' AND title = 'Growth Hacking Experiments';

UPDATE user_journeys SET description = 'Design a viral or referral loop: invite flows, incentives, and tracking so growth compounds.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["K-factor or invite rate","Viral cycle time","Referral signups","Cost per invite"]'::jsonb, primary_workflow_template_name = 'Product Launch Workflow', suggested_workflows = '["Social Media Campaign Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 0.5+ K-factor). Timeline?', category = 'marketing' WHERE persona = 'startup' AND title = 'Viral Loop Design';

UPDATE user_journeys SET description = 'Launch a referral program: mechanics, rewards, and tracking to grow through existing users.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Referrals sent","Conversion rate","Cost per acquisition","Program ROI"]'::jsonb, primary_workflow_template_name = 'Partnership Development', suggested_workflows = '["Email Nurture Sequence"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 20% of signups from referral). Timeline?', category = 'marketing' WHERE persona = 'startup' AND title = 'Referral Program V1';

UPDATE user_journeys SET description = 'Launch on Product Hunt: prepare page, rally community, and maximize visibility and upvotes.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Launch day rank","Upvotes","Signups from PH","Follow-up traffic"]'::jsonb, primary_workflow_template_name = 'Product Launch Campaign', suggested_workflows = '["Social Media Campaign Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. top 5 product of the day). Timeline?', category = 'marketing' WHERE persona = 'startup' AND title = 'Product Hunt Launch';

UPDATE user_journeys SET description = 'Get coverage in TechCrunch or similar: story angle, outreach, and follow-up to land the piece.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Pitch sent","Response rate","Article published","Traffic/conversions"]'::jsonb, primary_workflow_template_name = 'Influencer Outreach', suggested_workflows = '["Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. one tier-1 mention). Timeline?', category = 'marketing' WHERE persona = 'startup' AND title = 'TechCrunch Outreach';

UPDATE user_journeys SET description = 'Create and optimize your AngelList (Wellfound) profile so investors and talent can find you.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Profile completeness","Views","Inbound interest","Applications"]'::jsonb, primary_workflow_template_name = 'Fundraising Round', suggested_workflows = '["Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. profile 100% complete). Timeline?', category = 'strategy' WHERE persona = 'startup' AND title = 'AngelList Profile';

UPDATE user_journeys SET description = 'Apply to Y Combinator or similar accelerator: application, interview prep, and post-application plan.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Application submitted","Interview invite","Accepted","Batch start"]'::jsonb, primary_workflow_template_name = 'Fundraising Round', suggested_workflows = '["Strategic Planning Cycle","Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. get accepted). Timeline?', category = 'strategy' WHERE persona = 'startup' AND title = 'YCombinator Application';

UPDATE user_journeys SET description = 'Prepare for an accelerator: materials, metrics, and team so you are ready for the program.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Application ready","Demo day prep","Mentor meetings","Graduation"]'::jsonb, primary_workflow_template_name = 'Fundraising Round', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. demo day ready). Timeline?', category = 'strategy' WHERE persona = 'startup' AND title = 'Accelerator Prep';

UPDATE user_journeys SET description = 'Prepare for a Series A round: metrics, narrative, data room, and process to close the round.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Data room ready","Meetings held","Term sheet","Closed"]'::jsonb, primary_workflow_template_name = 'Fundraising Round', suggested_workflows = '["Strategic Planning Cycle","Merger & Acquisition (M&A)"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. close $X Series A). Timeline?', category = 'strategy' WHERE persona = 'startup' AND title = 'Series A Prep';

UPDATE user_journeys SET description = 'Evaluate a strategic pivot: data, options, and decision framework to change direction if needed.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Data reviewed","Options evaluated","Decision made","Communication plan"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Competitor Analysis Workflow","Initiative Framework"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. clear go/no-go and next steps). Timeline?', category = 'strategy' WHERE persona = 'startup' AND title = 'Strategic Pivot Analysis';

UPDATE user_journeys SET description = 'Run customer discovery interviews: find users, ask the right questions, and synthesize insights.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Interviews conducted","Insights documented","Patterns identified","Actions taken"]'::jsonb, primary_workflow_template_name = 'Lead Generation Workflow', suggested_workflows = '["Win/Loss Analysis"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 20 interviews, 5 key insights). Timeline?', category = 'sales' WHERE persona = 'startup' AND title = 'Customer Discovery Interviews';

UPDATE user_journeys SET description = 'Analyze why customers leave: segment churn, identify reasons, and act to retain and improve.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Churn rate","Reasons coded","Cohort analysis","Retention improved"]'::jsonb, primary_workflow_template_name = 'Churn Prevention', suggested_workflows = '["Win/Loss Analysis","Pipeline Review"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 10% monthly churn to 5%). Timeline?', category = 'sales' WHERE persona = 'startup' AND title = 'Churn Analysis';

UPDATE user_journeys SET description = 'Reduce and optimize server and infrastructure costs without sacrificing reliability.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Monthly spend","Cost per user","Uptime","Savings achieved"]'::jsonb, primary_workflow_template_name = 'Budget Planning', suggested_workflows = '["Financial Reporting"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 20% cost reduction). Timeline?', category = 'operations' WHERE persona = 'startup' AND title = 'Server Cost Optimization';

UPDATE user_journeys SET description = 'Implement an analytics stack: events, dashboards, and reporting so you can measure product and growth.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Events instrumented","Dashboards live","Key metrics tracked","Team adoption"]'::jsonb, primary_workflow_template_name = 'Analytics Implementation', suggested_workflows = '["Data Pipeline Setup"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 10 core events, 3 dashboards). Timeline?', category = 'operations' WHERE persona = 'startup' AND title = 'Analytics Stack Setup';

UPDATE user_journeys SET description = 'Build internal dashboards for ops, support, or growth so the team can monitor and act on data.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Dashboards built","Daily active viewers","Decisions from data","Refresh cadence"]'::jsonb, primary_workflow_template_name = 'Dashboard Creation', suggested_workflows = '["Analytics Implementation"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 3 dashboards, updated daily). Timeline?', category = 'operations' WHERE persona = 'startup' AND title = 'Internal Dashboard Build';

UPDATE user_journeys SET description = 'Create and maintain a knowledge base: docs, FAQs, and runbooks so the team and users can self-serve.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Articles published","Search success rate","Deflection rate","Updates per month"]'::jsonb, primary_workflow_template_name = 'Knowledge Base Update', suggested_workflows = '["Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like? (e.g. 50 articles, 30% support deflection). Timeline?', category = 'operations' WHERE persona = 'startup' AND title = 'Knowledge Base Create';

COMMIT;
