-- Migration: 0043_enrich_sme_journeys.sql
-- Enrich all 40 SME user journeys with descriptions, stages, KPIs, workflow mapping, outcomes_prompt.

BEGIN;

-- 5-phase stages (aligned with initiative framework)
-- Each journey gets: description, stages, kpis, primary_workflow_template_name, suggested_workflows, outcomes_prompt, category

UPDATE user_journeys SET description = 'Run a fair, consistent performance review cycle: set goals, collect feedback, and align ratings and development plans.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Reviews completed on time","Goals aligned","Feedback collected","Development plans documented"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Win/Loss Analysis","Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'sme' AND title = 'Performance Review Cycle';

UPDATE user_journeys SET description = 'Optimize supply chain: map suppliers, reduce cost and risk, and improve delivery and inventory turnover.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Supplier count","Lead time","Cost savings","Inventory turnover"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Vendor Onboarding","Pipeline Review"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'sme' AND title = 'Supply Chain Optimization';

UPDATE user_journeys SET description = 'Expand into a new geographic or vertical market: research, pilot, and scale with clear entry criteria and KPIs.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Market size validated","Pilot revenue","Local partnerships","Market share"]'::jsonb, primary_workflow_template_name = 'Competitor Analysis Workflow', suggested_workflows = '["Lead Generation Workflow","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'sme' AND title = 'New Market Expansion';

UPDATE user_journeys SET description = 'Plan and allocate department budgets: align to strategy, get approval, and track spend against plan.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Budget approved","Variance to plan","Forecast accuracy","Cost per unit"]'::jsonb, primary_workflow_template_name = 'Budget Planning', suggested_workflows = '["Financial Reporting","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'finance' WHERE persona = 'sme' AND title = 'Department Budgeting';

UPDATE user_journeys SET description = 'Build a management training program: identify skills gaps, design curriculum, and roll out so leaders perform consistently.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Managers trained","Satisfaction score","Behavior change","Promotion from within"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Content Creation Workflow","Recruitment Pipeline"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'sme' AND title = 'Management Training Program';

UPDATE user_journeys SET description = 'Launch a diversity and inclusion initiative: assess current state, set goals, and embed inclusive practices across hiring and culture.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["D&I metrics baseline","Representation goals","Training completed","Retention by group"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Content Creation Workflow","Win/Loss Analysis"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'sme' AND title = 'Diversity & Inclusion Initiative';

UPDATE user_journeys SET description = 'Launch an employee wellness program: survey needs, choose offerings, and roll out to improve health and engagement.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Participation rate","Satisfaction score","Absenteeism change","Turnover impact"]'::jsonb, primary_workflow_template_name = 'Customer Onboarding', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'sme' AND title = 'Employee Wellness Program';

UPDATE user_journeys SET description = 'Define and communicate office hybrid policy: balance flexibility and collaboration, document rules, and roll out fairly.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Policy published","Employee acknowledgment","Compliance rate","Engagement score"]'::jsonb, primary_workflow_template_name = 'Policy Update', suggested_workflows = '["Strategic Planning Cycle","Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'sme' AND title = 'Office Hybrid Policy';

UPDATE user_journeys SET description = 'Manage IT assets end-to-end: procure, deploy, maintain, and retire devices and software with clear lifecycle and cost control.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Asset inventory accuracy","Refresh cycle","Cost per seat","Security compliance"]'::jsonb, primary_workflow_template_name = 'Vendor Onboarding', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'sme' AND title = 'IT Asset Lifecycle';

UPDATE user_journeys SET description = 'Conduct a cybersecurity audit: assess risks, test controls, and remediate gaps to protect data and systems.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Findings identified","Critical items remediated","Policy updates","Staff training"]'::jsonb, primary_workflow_template_name = 'GDPR Compliance Audit', suggested_workflows = '["Policy Update","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'sme' AND title = 'Cybersecurity Audit';

UPDATE user_journeys SET description = 'Create and test a disaster recovery plan: define RTO/RPO, document procedures, and run a drill so the business can recover.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["DR plan documented","Backup tested","Drill completed","Recovery time met"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Policy Update","Crisis Management Response"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'sme' AND title = 'Disaster Recovery Plan';

UPDATE user_journeys SET description = 'Migrate to a new CRM without losing data or momentum: plan, migrate, train, and cut over cleanly.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Data migrated accurately","User adoption","Go-live date","Sales cycle unchanged"]'::jsonb, primary_workflow_template_name = 'Vendor Onboarding', suggested_workflows = '["Strategic Planning Cycle","Customer Onboarding"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'sme' AND title = 'CRM Migration';

UPDATE user_journeys SET description = 'Implement an ERP system: select vendor, configure processes, migrate data, and go live with minimal disruption.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Modules live","Data accuracy","User training","Process adoption"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Vendor Onboarding","Budget Planning"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'sme' AND title = 'ERP Implementation';

UPDATE user_journeys SET description = 'Design and implement a sales commission structure: align incentives to strategy, model cost, and communicate clearly.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Plan approved","Payout accuracy","Sales alignment","Attrition impact"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Deal Closing","Pipeline Review"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'sales' WHERE persona = 'sme' AND title = 'Sales Commission Structure';

UPDATE user_journeys SET description = 'Build a customer success playbook: define health metrics, lifecycle stages, and playbooks to reduce churn and grow expansion.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Playbooks documented","Health score coverage","Churn rate","NRR"]'::jsonb, primary_workflow_template_name = 'Customer Onboarding', suggested_workflows = '["Churn Prevention","Account Renewal"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'support' WHERE persona = 'sme' AND title = 'Customer Success Playbook';

UPDATE user_journeys SET description = 'Run an NPS survey campaign: design questions, send at the right moment, close the loop, and act on insights.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Response rate","NPS score","Follow-up rate","Actions taken"]'::jsonb, primary_workflow_template_name = 'Win/Loss Analysis', suggested_workflows = '["Email Nurture Sequence","Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'support' WHERE persona = 'sme' AND title = 'NPS Survey Campaign';

UPDATE user_journeys SET description = 'Refresh your brand identity: audit current perception, define new direction, and roll out across touchpoints consistently.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Guidelines published","Touchpoints updated","Awareness score","Consistency audit"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Social Media Campaign Workflow","SEO Optimization Audit"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'marketing' WHERE persona = 'sme' AND title = 'Brand Refresh';

UPDATE user_journeys SET description = 'Replatform your website: define requirements, choose platform, migrate content, and launch with improved performance and SEO.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Launch date","Uptime","Page speed","Traffic maintained"]'::jsonb, primary_workflow_template_name = 'Product Launch Workflow', suggested_workflows = '["Content Creation Workflow","SEO Optimization Audit"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'marketing' WHERE persona = 'sme' AND title = 'Website Replatforming';

UPDATE user_journeys SET description = 'Consolidate vendors: map current spend, identify overlap, renegotiate or switch, and reduce cost and complexity.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Vendors reduced","Savings achieved","Contract compliance","Single points of failure removed"]'::jsonb, primary_workflow_template_name = 'Vendor Onboarding', suggested_workflows = '["Strategic Planning Cycle","Pipeline Review"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'sme' AND title = 'Vendor Consolidation';

UPDATE user_journeys SET description = 'Define and implement a procurement policy: approval thresholds, preferred suppliers, and controls to manage spend and risk.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Policy published","Compliance rate","Savings from preferred","Cycle time"]'::jsonb, primary_workflow_template_name = 'Policy Update', suggested_workflows = '["Contract Review","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'sme' AND title = 'Procurement Policy';

UPDATE user_journeys SET description = 'Update expense policy: set rules, approval flows, and limits so spend is controlled and compliant.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Policy published","Acknowledgment rate","Expense compliance","Reimbursement cycle"]'::jsonb, primary_workflow_template_name = 'Policy Update', suggested_workflows = '["Budget Planning","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'sme' AND title = 'Expense Policy Update';

UPDATE user_journeys SET description = 'Update travel policy: balance cost control with employee needs, document rules, and ensure compliance and duty of care.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Policy published","Travel spend vs budget","Compliance rate","Booking channel adoption"]'::jsonb, primary_workflow_template_name = 'Policy Update', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'sme' AND title = 'Travel Policy Update';

UPDATE user_journeys SET description = 'Evaluate and optimize recruitment agency spend: track cost per hire, quality, and time to fill; consolidate or renegotiate.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Cost per hire","Time to fill","Quality of hire","Agency count"]'::jsonb, primary_workflow_template_name = 'Recruitment Pipeline', suggested_workflows = '["Win/Loss Analysis","Pipeline Review"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'sme' AND title = 'Recruitment Agency ROI';

UPDATE user_journeys SET description = 'Launch an internship program: define roles, partner with schools, run a structured program, and convert top performers.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Interns hired","Conversion rate","Manager satisfaction","Pipeline for roles"]'::jsonb, primary_workflow_template_name = 'Recruitment Pipeline', suggested_workflows = '["Employee Onboarding","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'sme' AND title = 'Internship Program';

UPDATE user_journeys SET description = 'Define and launch a corporate social responsibility program: align to values, choose initiatives, and communicate impact.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["CSR pillars defined","Programs launched","Employee participation","Impact reported"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Content Creation Workflow","Partnership Development"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'sme' AND title = 'Corporate Social Responsibility';

UPDATE user_journeys SET description = 'Produce a sustainability report: gather data, align to frameworks, and publish progress on environmental and social goals.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Report published","Metrics covered","Stakeholder feedback","Targets set"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Strategic Planning Cycle","Financial Reporting"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'sme' AND title = 'Sustainability Report';

UPDATE user_journeys SET description = 'Design and publish your annual report: narrative, financials, and governance in a clear, compliant format.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Report published on time","Sections completed","Compliance check","Distribution"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Financial Reporting","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'sme' AND title = 'Annual Report Design';

UPDATE user_journeys SET description = 'Create a town hall meeting deck: align messaging, share results and strategy, and engage employees with Q&A.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Deck delivered","Attendance","Engagement score","Action items followed up"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'sme' AND title = 'Town Hall Meeting Deck';

UPDATE user_journeys SET description = 'Plan and run a leadership offsite: set objectives, agenda, and outcomes so the team aligns on strategy and culture.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Offsite completed","Objectives met","Decisions documented","Follow-up actions"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'sme' AND title = 'Leadership Offsite';

UPDATE user_journeys SET description = 'Build succession plans for key roles: identify talent, develop readiness, and document so transitions are smooth.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Roles covered","Readiness assessed","Development plans","Internal fill rate"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Recruitment Pipeline","Win/Loss Analysis"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'sme' AND title = 'Succession Planning';

UPDATE user_journeys SET description = 'Implement key account management: segment accounts, assign owners, define playbooks, and grow revenue from top customers.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Accounts segmented","Coverage model","Revenue from key accounts","Churn in segment"]'::jsonb, primary_workflow_template_name = 'Account Renewal', suggested_workflows = '["Pipeline Review","Deal Closing"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'sales' WHERE persona = 'sme' AND title = 'Key Account Management';

UPDATE user_journeys SET description = 'Develop a partner channel strategy: identify partners, define GTM, enable and track so channel contributes to revenue.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Partners recruited","Channel revenue","Partner satisfaction","Deals sourced"]'::jsonb, primary_workflow_template_name = 'Partnership Development', suggested_workflows = '["Lead Generation Workflow","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'sme' AND title = 'Partner Channel Strategy';

UPDATE user_journeys SET description = 'Launch a reseller program: define terms, recruit resellers, enable and support so they sell and implement successfully.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Resellers onboarded","Revenue via resellers","Training completed","Support tickets"]'::jsonb, primary_workflow_template_name = 'Partnership Development', suggested_workflows = '["Deal Closing","Vendor Onboarding"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'sales' WHERE persona = 'sme' AND title = 'Reseller Program';

UPDATE user_journeys SET description = 'Revamp your loyalty program: design rewards, mechanics, and tech so customers engage more and retention improves.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Program launched","Enrollment rate","Redemption rate","Retention lift"]'::jsonb, primary_workflow_template_name = 'Email Nurture Sequence', suggested_workflows = '["Social Media Campaign Workflow","A/B Testing Workflow"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'marketing' WHERE persona = 'sme' AND title = 'Loyalty Program Revamp';

UPDATE user_journeys SET description = 'Analyze and improve inventory turnover: segment SKUs, set targets, and adjust buying and promotions to optimize working capital.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Turnover ratio","Days on hand","Obsolescence","Working capital"]'::jsonb, primary_workflow_template_name = 'Pipeline Review', suggested_workflows = '["Financial Reporting","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'sme' AND title = 'Inventory Turnover Analysis';

UPDATE user_journeys SET description = 'Build and maintain cash flow forecasts: model scenarios, update regularly, and align with funding and operations.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Forecast accuracy","Update cadence","Scenarios modeled","Liquidity headroom"]'::jsonb, primary_workflow_template_name = 'Financial Reporting', suggested_workflows = '["Budget Planning","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'finance' WHERE persona = 'sme' AND title = 'Cash Flow Forecasting';

UPDATE user_journeys SET description = 'Refinance debt to improve terms: assess options, model savings, negotiate with lenders, and close without disrupting operations.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Deal closed","Interest savings","Covenants improved","Documentation complete"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Financial Reporting","Contract Review"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'finance' WHERE persona = 'sme' AND title = 'Debt Refinancing';

UPDATE user_journeys SET description = 'Renew insurance policies: review coverage, compare quotes, and secure renewal with the right balance of cost and protection.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Policies renewed","Coverage adequacy","Premium vs prior","Claims readiness"]'::jsonb, primary_workflow_template_name = 'Vendor Onboarding', suggested_workflows = '["Contract Review","Budget Planning"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'sme' AND title = 'Insurance Renewal';

UPDATE user_journeys SET description = 'Review legal retainer arrangements: assess usage, compare firms, and optimize for cost and quality of support.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Retainer reviewed","Spend vs budget","Response time","Scope clarity"]'::jsonb, primary_workflow_template_name = 'Contract Review', suggested_workflows = '["Strategic Planning Cycle","Pipeline Review"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'legal' WHERE persona = 'sme' AND title = 'Legal Retainer Review';

UPDATE user_journeys SET description = 'Roll out compliance training: identify requirements, design or source content, and ensure completion and certification.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Training completed","Completion rate","Certification","Audit readiness"]'::jsonb, primary_workflow_template_name = 'Policy Update', suggested_workflows = '["GDPR Compliance Audit","Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'legal' WHERE persona = 'sme' AND title = 'Compliance Training';

COMMIT;
