-- Migration: 0044_enrich_enterprise_journeys.sql
-- Enrich all 40 Enterprise user journeys with descriptions, stages, KPIs, workflow mapping, outcomes_prompt.

BEGIN;

-- 5-phase stages (aligned with initiative framework)
-- Each journey gets: description, stages, kpis, primary_workflow_template_name, suggested_workflows, outcomes_prompt, category

UPDATE user_journeys SET description = 'Conduct a comprehensive multi-jurisdiction compliance review: assess gaps, remediate, and document controls.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Jurisdictions covered","Gap closure rate","Audit findings","Policy attestation"]'::jsonb, primary_workflow_template_name = 'GDPR Compliance Audit', suggested_workflows = '["Strategic Planning Cycle","Policy Update"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'compliance' WHERE persona = 'enterprise' AND title = 'Global Compliance Audit';

UPDATE user_journeys SET description = 'Successfully integrate an acquired company: align people, process, and systems post-merger.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Day-one readiness","Synergy captured","Retention rate","Systems integrated"]'::jsonb, primary_workflow_template_name = 'Merger & Acquisition (M&A)', suggested_workflows = '["Strategic Planning Cycle","Contract Review"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'enterprise' AND title = 'Merger & Acquisition Integration';

UPDATE user_journeys SET description = 'Roll out ERP enterprise-wide: design to-be state, configure, pilot, and deploy in waves.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Waves completed","User adoption","Process automation","Go-live on time"]'::jsonb, primary_workflow_template_name = 'Roadmap Planning', suggested_workflows = '["Strategic Planning Cycle","Vendor Onboarding"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'enterprise' AND title = 'Enterprise-wide ERP Rollout';

UPDATE user_journeys SET description = 'Lead digital transformation: assess maturity, define vision, pilot, and scale across the organization.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Maturity score","Pilot ROI","Adoption rate","Business impact"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Roadmap Planning","Initiative Framework"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'enterprise' AND title = 'Digital Transformation Roadmap';

UPDATE user_journeys SET description = 'Define and execute cloud migration: assess workloads, choose platforms, and migrate with minimal disruption.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Workloads migrated","Cost optimization","Uptime","Security posture"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Roadmap Planning","Data Pipeline Setup"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'enterprise' AND title = 'Cloud Migration Strategy';

UPDATE user_journeys SET description = 'Design and implement enterprise data lake: ingestion, storage, governance, and analytics-ready data.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Data sources connected","Quality rules","Query performance","Consumer adoption"]'::jsonb, primary_workflow_template_name = 'Data Pipeline Setup', suggested_workflows = '["Data Governance Audit","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'enterprise' AND title = 'Data Lake Architecture';

UPDATE user_journeys SET description = 'Establish responsible AI governance: policies, risk controls, and oversight across use cases.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Policy approved","Use cases assessed","Risk register","Audit readiness"]'::jsonb, primary_workflow_template_name = 'Data Governance Audit', suggested_workflows = '["Policy Update","Initiative Framework"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'compliance' WHERE persona = 'enterprise' AND title = 'AI Governance Framework';

UPDATE user_journeys SET description = 'Consolidate global payroll: unify systems, policies, and reporting across regions.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Countries consolidated","Error rate","Cycle time","Compliance rate"]'::jsonb, primary_workflow_template_name = 'Payroll Processing', suggested_workflows = '["Strategic Planning Cycle","Vendor Onboarding"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'enterprise' AND title = 'Global Payroll Consolidation';

UPDATE user_journeys SET description = 'Stand up a shared services center: scope functions, design operating model, and transition work.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Functions in scope","Cost savings","SLAs met","Customer satisfaction"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Vendor Onboarding","Roadmap Planning"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'enterprise' AND title = 'Shared Services Center';

UPDATE user_journeys SET description = 'Create a center of excellence: define scope, charter, resourcing, and rollout to the business.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Charter approved","Projects supported","Adoption rate","Capability uplift"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Roadmap Planning","Initiative Framework"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'enterprise' AND title = 'Center of Excellence Setup';

UPDATE user_journeys SET description = 'Launch an internal innovation lab: mandate, funding, governance, and pipeline of experiments.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Lab launched","Projects in pipeline","Pilots scaled","ROI delivered"]'::jsonb, primary_workflow_template_name = 'Initiative Framework', suggested_workflows = '["Strategic Planning Cycle","Partnership Development"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'product' WHERE persona = 'enterprise' AND title = 'Innovation Lab Launch';

UPDATE user_journeys SET description = 'Set up corporate venture capital: thesis, process, and portfolio to drive strategic innovation.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Thesis defined","Deals screened","Investments made","Strategic alignment"]'::jsonb, primary_workflow_template_name = 'Partnership Development', suggested_workflows = '["Fundraising Round","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'enterprise' AND title = 'Corporate Venture Capital';

UPDATE user_journeys SET description = 'Review and strengthen board governance: charters, committees, and compliance with best practices.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Charters updated","Committee effectiveness","Compliance score","Director onboarding"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Contract Review","Policy Update"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'enterprise' AND title = 'Board Governance Review';

UPDATE user_journeys SET description = 'Deliver investor relations quarterly: materials, earnings, and engagement with analysts and shareholders.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Earnings on time","Analyst coverage","Shareholder satisfaction","Narrative consistency"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Strategic Planning Cycle","Quarterly Business Review (QBR)"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'enterprise' AND title = 'Investor Relations Quarterly';

UPDATE user_journeys SET description = 'Define and implement ESG strategy: environmental, social, and governance goals and reporting.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["ESG goals set","Reporting published","Ratings improvement","Stakeholder alignment"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Content Creation Workflow","Policy Update"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'strategy' WHERE persona = 'enterprise' AND title = 'ESG Strategy';

UPDATE user_journeys SET description = 'Produce diversity annual report: metrics, narrative, and progress on representation and inclusion.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Report published","Metrics tracked","Goals progress","External recognition"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Strategic Planning Cycle","Policy Update"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'enterprise' AND title = 'Diversity Annual Report';

UPDATE user_journeys SET description = 'Design and run global mobility program: assignments, relocation, tax, and policy.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Policy documented","Assignments supported","Compliance rate","Employee satisfaction"]'::jsonb, primary_workflow_template_name = 'Policy Update', suggested_workflows = '["Employee Onboarding","Contract Review"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'enterprise' AND title = 'Global Mobility Program';

UPDATE user_journeys SET description = 'Review and align executive compensation: benchmarks, structure, and governance.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Benchmark completed","Structure approved","Say-on-pay outcome","Retention achieved"]'::jsonb, primary_workflow_template_name = 'Performance Review', suggested_workflows = '["Policy Update","Contract Review"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'enterprise' AND title = 'Executive Compensation Review';

UPDATE user_journeys SET description = 'Prepare and execute union negotiation strategy: positions, timeline, and agreement ratification.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Strategy approved","Negotiations completed","Agreement ratified","Labor peace"]'::jsonb, primary_workflow_template_name = 'Contract Review', suggested_workflows = '["Policy Update","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'enterprise' AND title = 'Union Negotiation Strategy';

UPDATE user_journeys SET description = 'Create crisis communication playbook: scenarios, spokespeople, and response templates.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Playbook published","Drills run","Response time","Stakeholder trust"]'::jsonb, primary_workflow_template_name = 'Crisis Management Response', suggested_workflows = '["Content Creation Workflow","Policy Update"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'support' WHERE persona = 'enterprise' AND title = 'Crisis Communication Playbook';

UPDATE user_journeys SET description = 'Establish cyber incident response: detection, containment, communication, and post-incident review.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Response plan tested","MTTR","Communication cadence","Lessons learned"]'::jsonb, primary_workflow_template_name = 'Incident Investigation', suggested_workflows = '["Crisis Management Response","Policy Update"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'compliance' WHERE persona = 'enterprise' AND title = 'Cyber Incident Response';

UPDATE user_journeys SET description = 'Run business continuity test: validate recovery procedures and update plans.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Test completed","RTO/RPO met","Gaps remediated","Plan updated"]'::jsonb, primary_workflow_template_name = 'Crisis Management Response', suggested_workflows = '["Strategic Planning Cycle","Initiative Framework"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'enterprise' AND title = 'Business Continuity Test';

UPDATE user_journeys SET description = 'Strengthen supply chain resilience: dual sourcing, inventory, and risk monitoring.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Critical suppliers mapped","Dual source %","Inventory levels","Disruption recovery"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Vendor Onboarding","Roadmap Planning"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'enterprise' AND title = 'Supply Chain Resilience';

UPDATE user_journeys SET description = 'Define global tax strategy: structure, transfer pricing, and compliance across jurisdictions.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Strategy documented","Effective rate","Audit outcomes","Compliance rate"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Tax Filing Prep","Financial Reporting"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'finance' WHERE persona = 'enterprise' AND title = 'Global Tax Strategy';

UPDATE user_journeys SET description = 'Conduct transfer pricing study: document intercompany pricing and align with regulations.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Study completed","Documentation filed","Adjustments avoided","Audit readiness"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Contract Review","Financial Reporting"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'finance' WHERE persona = 'enterprise' AND title = 'Transfer Pricing Study';

UPDATE user_journeys SET description = 'Review brand architecture: master brand, sub-brands, and guidelines for consistency.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Architecture documented","Guidelines published","Adoption rate","Brand strength"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Strategic Planning Cycle","Ad Campaign Management"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'marketing' WHERE persona = 'enterprise' AND title = 'Brand Architecture Review';

UPDATE user_journeys SET description = 'Execute global marketing campaign: creative, channels, and measurement across regions.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Campaign launched","Reach and engagement","Conversion rate","Brand lift"]'::jsonb, primary_workflow_template_name = 'Ad Campaign Management', suggested_workflows = '["Social Media Campaign Workflow","Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'marketing' WHERE persona = 'enterprise' AND title = 'Global Marketing Campaign';

UPDATE user_journeys SET description = 'Rationalize product portfolio: assess fit, sunset legacy, and focus on strategic offerings.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Portfolio mapped","Decisions made","Sunset completed","Revenue concentration"]'::jsonb, primary_workflow_template_name = 'Roadmap Planning', suggested_workflows = '["Strategic Planning Cycle","Competitor Analysis Workflow"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'product' WHERE persona = 'enterprise' AND title = 'Product Portfolio Rationalization';

UPDATE user_journeys SET description = 'Sunset legacy systems: plan migration, decommission, and archive data safely.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Systems retired","Data archived","Cost saved","No disruption"]'::jsonb, primary_workflow_template_name = 'Roadmap Planning', suggested_workflows = '["Strategic Planning Cycle","Feature Development"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'enterprise' AND title = 'Legacy System Sunsetting';

UPDATE user_journeys SET description = 'Modernize mainframe workloads: assess, migrate to cloud or hybrid, and decommission where appropriate.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Workloads migrated","Performance maintained","Cost reduced","Risk mitigated"]'::jsonb, primary_workflow_template_name = 'Roadmap Planning', suggested_workflows = '["Feature Development","Data Pipeline Setup"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'enterprise' AND title = 'Mainframe Modernization';

UPDATE user_journeys SET description = 'Implement zero trust security model: identity, device, and network controls.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Policies defined","Controls deployed","Verification rate","Incident reduction"]'::jsonb, primary_workflow_template_name = 'Policy Update', suggested_workflows = '["Data Governance Audit","Initiative Framework"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'compliance' WHERE persona = 'enterprise' AND title = 'Zero Trust Security Model';

UPDATE user_journeys SET description = 'Achieve GDPR and CCPA compliance: data mapping, consent, rights, and documentation.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Data map complete","Consent mechanism","Rights response time","Audit passed"]'::jsonb, primary_workflow_template_name = 'GDPR Compliance Audit', suggested_workflows = '["Policy Update","Data Governance Audit"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'compliance' WHERE persona = 'enterprise' AND title = 'GDPR/CCPA Compliance';

UPDATE user_journeys SET description = 'Deploy whistleblower hotline: policy, channel, and case handling with confidentiality.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Hotline live","Cases handled","Retaliation zero","Awareness rate"]'::jsonb, primary_workflow_template_name = 'Policy Update', suggested_workflows = '["Contract Review","Initiative Framework"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'compliance' WHERE persona = 'enterprise' AND title = 'Whistleblower Hotline';

UPDATE user_journeys SET description = 'Run internal audit cycle: plan, execute, report, and track remediation.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Audit plan completed","Findings reported","Remediation %","Board reporting"]'::jsonb, primary_workflow_template_name = 'Quality Assurance Audit', suggested_workflows = '["Data Governance Audit","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'compliance' WHERE persona = 'enterprise' AND title = 'Internal Audit Cycle';

UPDATE user_journeys SET description = 'Review strategic vendors: performance, risk, contract, and consolidation opportunities.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Vendors reviewed","Savings identified","Risk mitigated","Contracts renewed"]'::jsonb, primary_workflow_template_name = 'Vendor Onboarding', suggested_workflows = '["Partnership Development","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'enterprise' AND title = 'Strategic Vendor Review';

UPDATE user_journeys SET description = 'Optimize real estate portfolio: footprint, leases, and workplace strategy.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Portfolio mapped","Cost per seat","Utilization rate","Lease flexibility"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Contract Review","Roadmap Planning"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'enterprise' AND title = 'Real Estate Portfolio';

UPDATE user_journeys SET description = 'Launch corporate university: curriculum, platform, and learning culture.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Curriculum defined","Completion rate","Skills uplift","Engagement score"]'::jsonb, primary_workflow_template_name = 'Content Creation Workflow', suggested_workflows = '["Employee Onboarding","Knowledge Base Update"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'enterprise' AND title = 'Corporate University';

UPDATE user_journeys SET description = 'Build leadership development program: assess, develop, and succession readiness.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Leaders assessed","Program completed","Promotions from within","Pipeline strength"]'::jsonb, primary_workflow_template_name = 'Performance Review', suggested_workflows = '["Employee Onboarding","Strategic Planning Cycle"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'hr' WHERE persona = 'enterprise' AND title = 'Leadership Development Program';

UPDATE user_journeys SET description = 'Implement change management framework: assess impact, communicate, train, and sustain adoption.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Framework adopted","Stakeholders engaged","Adoption rate","Benefits realized"]'::jsonb, primary_workflow_template_name = 'Strategic Planning Cycle', suggested_workflows = '["Initiative Framework","Roadmap Planning"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'enterprise' AND title = 'Change Management Framework';

UPDATE user_journeys SET description = 'Establish global knowledge management: capture, organize, and enable findability and reuse.', stages = '[{"name":"Ideation","status":"pending"},{"name":"Validation","status":"pending"},{"name":"Prototype","status":"pending"},{"name":"Build","status":"pending"},{"name":"Scale","status":"pending"}]'::jsonb, kpis = '["Content captured","Search success","Reuse rate","Time to competency"]'::jsonb, primary_workflow_template_name = 'Knowledge Base Update', suggested_workflows = '["Strategic Planning Cycle","Content Creation Workflow"]'::jsonb, outcomes_prompt = 'What does success look like for this initiative? Any timeline or key milestones?', category = 'operations' WHERE persona = 'enterprise' AND title = 'Global Knowledge Management';

COMMIT;
