-- Skill usage telemetry for runtime audit and cleanup decisions

CREATE TABLE IF NOT EXISTS skill_usage_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    session_id TEXT,
    duration_ms INTEGER NOT NULL DEFAULT 0,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_skill_usage_log_skill_created_at
ON skill_usage_log(skill_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_skill_usage_log_user_created_at
ON skill_usage_log(user_id, created_at DESC);

ALTER TABLE skill_usage_log ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'skill_usage_log'
          AND policyname = 'Service role manages skill usage log'
    ) THEN
        CREATE POLICY "Service role manages skill usage log"
        ON skill_usage_log FOR ALL
        TO service_role
        USING (true)
        WITH CHECK (true);
    END IF;
END $$;

