-- GAP-05/06/07/09/10 reconciliation:
-- - ensure missing runtime tables exist in live environments
-- - tighten public-read policies
-- - fix advisor warnings for memory trigger function search_path
-- - normalize memory RLS auth checks

CREATE TABLE IF NOT EXISTS public.finance_assumptions_ledger (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    assumption_type TEXT NOT NULL CHECK (assumption_type IN ('reporting_rule', 'scenario_assumption', 'benchmark_set')),
    assumption_key TEXT NOT NULL,
    label TEXT NOT NULL,
    scope TEXT NOT NULL DEFAULT 'global',
    value JSONB NOT NULL DEFAULT '{}'::jsonb,
    summary TEXT NOT NULL,
    notes TEXT,
    source TEXT NOT NULL DEFAULT 'manual',
    effective_start TIMESTAMPTZ,
    effective_end TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_finance_assumptions_ledger_user_type
    ON public.finance_assumptions_ledger(user_id, assumption_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_finance_assumptions_ledger_user_scope
    ON public.finance_assumptions_ledger(user_id, scope, created_at DESC);

ALTER TABLE public.finance_assumptions_ledger ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own finance assumptions" ON public.finance_assumptions_ledger;
DROP POLICY IF EXISTS "Users can insert own finance assumptions" ON public.finance_assumptions_ledger;
DROP POLICY IF EXISTS "Users can update own finance assumptions" ON public.finance_assumptions_ledger;
DROP POLICY IF EXISTS "Users can delete own finance assumptions" ON public.finance_assumptions_ledger;
DROP POLICY IF EXISTS "Service role manages finance assumptions" ON public.finance_assumptions_ledger;

CREATE POLICY "Users can view own finance assumptions"
ON public.finance_assumptions_ledger FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can insert own finance assumptions"
ON public.finance_assumptions_ledger FOR INSERT TO authenticated
WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can update own finance assumptions"
ON public.finance_assumptions_ledger FOR UPDATE TO authenticated
USING ((SELECT auth.uid()) = user_id)
WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can delete own finance assumptions"
ON public.finance_assumptions_ledger FOR DELETE TO authenticated
USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Service role manages finance assumptions"
ON public.finance_assumptions_ledger FOR ALL TO service_role
USING (true)
WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.skill_usage_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    session_id TEXT,
    duration_ms INTEGER NOT NULL DEFAULT 0,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_skill_usage_log_skill_created_at
ON public.skill_usage_log(skill_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_skill_usage_log_user_created_at
ON public.skill_usage_log(user_id, created_at DESC);

ALTER TABLE public.skill_usage_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages skill usage log" ON public.skill_usage_log;
CREATE POLICY "Service role manages skill usage log"
ON public.skill_usage_log FOR ALL TO service_role
USING (true)
WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.update_user_memory_facts_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_memory_episodes_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;

DROP POLICY IF EXISTS "Users can view own memory facts" ON public.user_memory_facts;
DROP POLICY IF EXISTS "Users can insert own memory facts" ON public.user_memory_facts;
DROP POLICY IF EXISTS "Users can update own memory facts" ON public.user_memory_facts;
DROP POLICY IF EXISTS "Users can delete own memory facts" ON public.user_memory_facts;

CREATE POLICY "Users can view own memory facts"
ON public.user_memory_facts FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can insert own memory facts"
ON public.user_memory_facts FOR INSERT TO authenticated
WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can update own memory facts"
ON public.user_memory_facts FOR UPDATE TO authenticated
USING ((SELECT auth.uid()) = user_id)
WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can delete own memory facts"
ON public.user_memory_facts FOR DELETE TO authenticated
USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "Users can CRUD their own memory episodes" ON public.memory_episodes;
DROP POLICY IF EXISTS "Users can view own memory episodes" ON public.memory_episodes;
DROP POLICY IF EXISTS "Users can insert own memory episodes" ON public.memory_episodes;
DROP POLICY IF EXISTS "Users can update own memory episodes" ON public.memory_episodes;
DROP POLICY IF EXISTS "Users can delete own memory episodes" ON public.memory_episodes;

CREATE POLICY "Users can view own memory episodes"
ON public.memory_episodes FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can insert own memory episodes"
ON public.memory_episodes FOR INSERT TO authenticated
WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can update own memory episodes"
ON public.memory_episodes FOR UPDATE TO authenticated
USING ((SELECT auth.uid()) = user_id)
WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can delete own memory episodes"
ON public.memory_episodes FOR DELETE TO authenticated
USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "Public read access for approval requests" ON public.approval_requests;
DROP POLICY IF EXISTS "Users can view own approval requests" ON public.approval_requests;

CREATE POLICY "Users can view own approval requests"
ON public.approval_requests FOR SELECT TO authenticated
USING (
    COALESCE(payload->>'requester_user_id', payload->>'user_id', '')
    = ((SELECT auth.uid())::text)
);

DROP POLICY IF EXISTS "Public read access for departments" ON public.departments;
DROP POLICY IF EXISTS "Authenticated read access for departments" ON public.departments;

CREATE POLICY "Authenticated read access for departments"
ON public.departments FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Users can view workflow marketplace reviews_select" ON public.workflow_template_marketplace_reviews;

CREATE POLICY "Users can view active workflow marketplace reviews"
ON public.workflow_template_marketplace_reviews FOR SELECT TO public
USING (
    EXISTS (
        SELECT 1
        FROM public.workflow_template_marketplace listing
        WHERE listing.id = listing_id
          AND listing.is_active = true
    )
);
